#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#


#
# Arroyo Quests
#
{100}{}{Kill the evil plants that infest Hakunin's garden.}
{110}{}{Obtain flint to have Mynoc sharpen your spear.}
{120}{}{Rescue Nagor's dog, Smoke, from the wilds.}
{130}{}{Retrieve the GECK for Arroyo.}
{140}{}{Find Vic the Trader.}

#
# Shady Sands Quests
#
{200}{}{Radiostacja Cienistych Piasków jest uszkodzona. Trzeba j¹ naprawiæ.}
{201}{}{Dwóch ludzi awanturuje siê w barze. Nale¿y ich wyprowadziæ.}
{202}{}{Niewolnicy produkuj¹cy alkohol pracuj¹ zbyt wolno. Trzeba im pomóc pracowaæ szybciej.}
{203}{}{Wokó³ obozowego kibelka nagromadzi³y siê szczury. Trzeba siê ich pozbyæ.}
{204}{}{ZnajdŸ zagubionego syna Anny w obozie.}
{205}{}{Wœród upraw wyros³y chwasty. Uporz¹dkowanie ogródka by³oby dobrym pomys³em.}
{206}{}{Brahminy narobi³y wokó³ siebie. Ktoœ musi to posprz¹taæ.}
{207}{}{Ko³owrotek od studni nie dzia³a. Coœ nale¿a³oby z tym zrobiæ.}
{208}{}{ZnajdŸ dowód przeciwko purpurowym ze szpitala.}
{209}{}{Razem z Khanami wyeleminuj purpurowych.}
{210}{}{Trzeba znowu uszkodziæ radiostacjê Felixa}

#
# Vault 13 Quests
#
{300}{}{ZnajdŸ leki na chore serce Syriusza.}
{301}{}{Rozwi¹¿ osobisty problem Edwarda.}