{199}{}{Pamiêtasz jak siê spotkaliœmy w górach? Od tego czasu mêczy mnie ca³y czas jedno pytanie. Jak uda³o wam siê im uciec? Przenikniêcie niezauwa¿onym miêdzy nimi graniczy³o z cudem.} #with maxstone
{200}{}{Pamiêtasz jak siê spotkaliœmy w górach? Od tego czasu mêczy mnie ca³y czas jedno pytanie. Jak uda³o ci siê im uciec? Przenikniêcie niezauwa¿onym miêdzy nimi graniczy³o z cudem.}
{201}{}{Nie pamiêtam. Chyba mam amnezjê…}
{202}{}{Pewien supermutant chcia³ nam pomóc. Dziwne co nie? Wspomina³, ¿ebym znalaz³ jak¹œ Tandi i przekaza³ jej, ¿eby ucieka³a. Otworzy³ klatki i kilkudziesiêciu z nas uciek³o.}


{210}{}{Su-per-mutant? Jeden z nich otworzy³ wam klatki? Jestem dalej oszo³omiony nowym Œwiatem, ale dalej pojawiaj¹ siê nowe rzeczy które mnie zadziwiaj¹. To te¿ znak, ¿e wielu zdo³a³o uciec i tu³aj¹ siê po Kalifornii. Powinniœmy braæ na to poprawkê.}
{211}{}{Nieistotne zatem. W ka¿dym razie jesteœmy cali i zdrowi.}
{213}{}{ A no i dobrze ciê widzieæ razem z Maxem. Co jak co, ale Max to wielka kupa miêœni, która zmia¿d¿y wszystko co napotka na swojej drodze.}

{214}{}{Jak w ogóle znaleŸliœcie to miejsce?}
{215}{}{By³em w jaskini.}#Quest
{216}{}{A jak z wami? Jak uda³o wam siê wydostaæ?}
{217}{}{Zamierzacie tutaj zostaæ?}
{218}{}{Rozejrzê siê jeszcze.}
{219}{}{Bêdê planowa³ odbicie krypty z r¹k supermutantów. Przy³¹czycie siê?}


{220}{}{Schowaliœmy siê razem z Ann¹ w szybie wentylacyjnym i przez kratkê obserwowaliœmy ich. Po kilku dniach nadarzy³a siê okazja i napadliœmy na dwóch zakonników, cia³a schowaliœmy i za³o¿yliœmy szaty. W ten sposób w miarê spokojnie opuœciliœmy kryptê. Chryste… Dalej nie mogê siê otrz¹sn¹æ, ¿e tu jesteœmy.}
{221}{}{Hej Max, a ty w ogóle coœ mówisz? Hê?}
{222}{}{Max chyba zosta³ postrzelony podczas ucieczki w szyjê i jak widaæ nie mo¿e przez to mówiæ. [Max ods³ania skrawek szyi zas³oniêty przez kombinezon.]}
{223}{}{Bêdziemy musieli znaleŸæ gdzieœ dobrego lekarza. Powrót do krypty nie wchodzi w grê. Nie wygl¹da to dobrze, ale jednoczeœnie nie wygl¹da to tragicznie.}

{230}{}{Nie widzê lepszego wyboru. W œwiecie zewnêtrznym… to znaczy w… w… *na pustkowiach* a¿ siê roi od niebezpieczeñstw. Powinniœmy tutaj zostaæ póki nie znajdziemy lepszego wyjœcia.}
{240}{}{Czyœ ty oszala³? Dopiero co uciek³em z piek³a i nie mam ochoty tam wracaæ. Poza tym jest nas tylko trzech… gdyby by³o nas z piêciuset to bym móg³ siê zacz¹æ zastanawiaæ.}
{250}{}{Wszystko za spraw¹ Vavro. Jego pradziadek mia³ tutaj wybudowaæ dom w górach. Dlaczego go o to nie zapytasz?}

{260}{}{Jakieœ nowe wieœci, albo jest coœ z czym mogê ci pomóc?}

#Cave
{300}{}{Tej tutaj, naszej? No i?! [Na twarzy Franza pojawia siê niepokój, który przechodzi w ¿¹danie dalszej czêœci.]}
{301}{}{W jaskini œpi¹ zwierzêta. To by³oby nic gdyby nie fakt, ¿e s¹ od nas 3 razy wiêksze.}

{310}{}{[Franz bierze g³êboki oddech, zadumany przechadza siê po pomieszczeniu by spocz¹æ na krzeœle. Zak³ada obie rêce za g³owê.] WysadŸmy jaskiniê. Gdzieœ na pewno znajdziemy materia³y wybuchowe.}
{311}{}{Nie mamy na to czasu. One mog¹ obudziæ siê w ka¿dej chwili. Poza tym ta jaskinia mog³aby siê nam do czegoœ póŸniej przydaæ. Zobaczê co mam i podzielê siê z wami.}
{312}{}{Dobra udam siê na pustkowia i znajdê coœ co nam pos³u¿y.}
{313}{}{Tak siê sk³ada, ¿e mam ze sob¹ dynamit. Zróbmy zadymê.}