#######################
### COMBAT INITIAL ####
#######################

{196}{}{Syriuszu, mi³o ciê znów widzieæ po d³ugiej roz³¹ce} #syriusz zaproponuje wspóln¹ podró¿ tobie i laurze
{197}{}{Jasperze}
{198}{}{Wykaza³eœ siê nie lada pracowitoœci¹}
{199}{}{Dostarczy³eœ mi informacji o wiosce na wschód st¹d, które nied³ugo wykorzystamy}

{200}{}{To jeden z nich, ³apcie go!} #capture him!
{201}{}{By³eœ wystawiony na Œwiat zewnêtrzny zbyt d³ugo, teraz jesteœ bezu¿yteczny. Zabiæ go!} #you were exposed, outside world
{202}{}{Nie przeszkadzaj mi, bracie}
{203}{}{Nie przeszkadzaj mi, siostro}

{204}{}{S¹ to cenne dane i nie szczêdzê tobie pochwa³, ale...}
{205}{}{...ale?}
{206}{}{Ale doskonajesz sobie sprawê czym grozi niesubordynacja wobec Jednoœci}
{207}{}{Syriuszu, nie...}
{208}{}{Jednoœæ nie dlatego przyjê³a tak¹ nazwê by jej cz³onkowie dzia³ali na w³asn¹ rêkê}
{209}{}{Jednoœæ dzia³a skoordynowanie i podlega jasnemu dowództwu, a ty naruszy³eœ jej G£ÓWN¥ ZASADÊ!}
{210}{}{Wiem! Wiem! Dlatego chcia³em siê wykazaæ!}
{211}{}{I wykaza³eœ siê}
{212}{}{Twoje zas³ugi bêd¹ zapisane w Ksiêdze Poœwiêcenia}
{213}{}{Niemniejednak musisz pos³u¿yæ za przyk³ad dla nastêpców}
{214}{}{Syriuszu, wiem, ¿e nie musisz tego robiæ!}
{215}{}{Wykonaæ}
#plasma ciuciu ciu ciu
{216}{}{Jak widzicie Jednoœci nie mo¿na interpretowaæ na swój sposób}
{217}{}{Jednoœæ jest silna swoj¹ stanowczoœci¹, nie ma miejsca na herezje}
{218}{}{Wiêc Jednoœæ wymrze dopiero wtedy kiedy zginie jej ostatni g³osiciel}
#6s
{219}{}{Wy dwaj - udacie siê na drugi poziom krypty by wspomóc doktora Rittingera w badaniach}
{220}{}{TERAZ}
#fadeout animate_run_to_tile
#fadein
{221}{}{Dla waszej dwójki bêdê mia³ bojowe zadanie}
{222}{}{Widzicie...}
{223}{}{Stary Syriusz ju¿ nie domaga i ma chore serce}
{224}{}{Aby utrzymaæ mnie przy ¿yciu bêdê potrzebowa³ leków}
{225}{}{Inaczej Porucznik ka¿e przerwaæ badania i zamieni wszystkich w supermutantów}
{226}{}{Rozpocznie siê ciemny okres dla nauki w Jednoœci}
{227}{}{Dlatego potrzebujê wasz¹ dwójkê byœcie wyruszyli na po³udnie i znaleŸli dla mnie leki na moje chore serce}
{228}{}{Mam mapê z nakreœlonymi miejscami}
{229}{}{Jedna z nich to pewien magazyn na po³udniu, druga to ju¿ nie przelewki - staro¿ytna baza.}
{230}{}{Pamiêtajcie by bez obecnoœci supermutantów nie poruszaæ siê po zachodzie}
{231}{}{Doskonale wiecie czym to grozi}
{232}{}{OdejdŸcie, nie mogê marnowaæ mojego cennego czasu}

{250}{}{AAAAAAAHHH!!!}

#######################
### HOLODISK QUEST  ###
#######################

{300}{}{Bracie, mam nadziejê, ¿e zdajesz sobie sprawê z tego czym grozi nieuzasadnione przerywanie mi badañ?}
{301}{}{Siostro, mam nadziejê, ¿e zdajesz sobie sprawê z tego czym grozi nieuzasadnione przerywanie mi badañ?}
{302}{}{Nie jestem twoim bratem.}
{303}{}{Nie jestem twoj¹ siostr¹.}
{304}{}{Przynios³em dla ciebie holodysk.}
{305}{}{Przynios³am dla ciebie holodysk.}
{306}{}{Chyba ju¿ pójdê.}

{310}{}{A wiêc musisz byæ szpiegiem! Stra¿e! Zabiæ j¹!}
{311}{}{A wiêc musisz byæ szpiegiem! Stra¿e! Zabiæ go!}
{312}{}{Nie! Zaczekaj, ja...}
{313}{}{Hej! To by³ ¿a...}

{320}{}{To coœ wa¿nego? Powinienem to teraz ods³uchaæ?}
{321}{}{Mam pewien holodysk, który kazane mi by³o ci przekazaæ.}

{330}{}{No dobra, spójrzmy na to.}
{331}{}{[GOTOWE]}
{332}{}{Drogi Syriuszu, jak ju¿ zapewne wiesz od³¹czy³em siê od was i uda³em siê na wschód, wiêc uznaliœcie to za zdradê...}
# fade out
{333}{}{... oraz mam nadziejê, ¿e przestaniecie uwa¿aæ mnie za zdrajcê i przyœlecie wsparcie. Pozdrowienia.}
{334}{}{***Ksszztt***}
{337}{}{A to on... jak wrzód na ty³ku...}
{340}{}{Na pewno zrobimy u¿ytek z tych informacyj}
{341}{}{Ale Jasper za niesubordynacjê wobec prze³o¿onych bêdzie ukarany by daæ przyk³ad innym}
{342}{}{Nie mo¿emy tolerowaæ braku pos³uszeñstwa}
{343}{}{Przeka¿ Jasperowi, ¿eby jak najprêdzej wraca³ i ¿e czeka na niego nagroda}
{344}{}{Za sprowadzenie go tutaj ja osobiœcie nagrodzê ciê dodatkowo}
{345}{}{A teraz pozwól nie zawracaæ mi g³owy i dokonaæ przemiany...}
#201

{347}{}{Oj, nie. Nigdzie nie pójdziesz. Za bezsensowne przerwanie moich badañ nale¿y ci siê kara!}

{350}{}{W porz¹dku. Jak chcesz mo¿esz jeszcze chwilê zostaæ i obserowaæ nowe narodziny, ale potem znikaj!}
{351}{}{Dobra.}

{500}{}{Z moim sercem nie jest najlepiej. Mam nadziejê, ¿e przybywacie z pigu³kami. Jeœli nie odejdŸcie...}
{501}{}{[OdejdŸ.]}
{502}{}{ZnaleŸliœmy leki o które prosi³eœ.}
{503}{}{Mo¿esz przypomn¹æ nam gdzie mamy szukaæ?}

{510}{}{Dziêkujê, macie moj¹ dozgonn¹ wdziêcznoœæ. Teraz ja siê zajmê badaniami, a wy czekajcie na kolejne polecenia.}
{520}{}{Przecie¿ dostaliœcie mapê z nakreœlonymi lokacyjami! IdŸcie i poszukajcie je!}

{530}{}{Za rozwi¹zanie problemu zdrowotnego Syriusza zdobywasz }
{531}{}{ punktów doœwiadczenia.}
{532}{}{Czas do Wielkiej Przemiany wyd³u¿a siê. SprawdŸ Pip-Boya.}

{600}{}{Spokojnie, dziecko}
{601}{}{Za chwilê bêdziesz lepsz¹ wersj¹ siebie}
{602}{}{Proszê, nie...}
{603}{}{No ja pierdolê!}
{604}{}{Powinno wyjœæ inaczej…}
{605}{}{Zabierzcie mi to coœ sprzed oczu}
