{300}{}{W Z³omowie by³a taka jedna sucz}
{301}{}{Mówiê wam takie mia³a ding-dony...}
{302}{}{A pierdziawa... ech...}
{303}{}{Mia³a kobita na czym siedzieæ}
{304}{}{Teraz pewnie zamienili j¹ w brzydk¹ wielk¹ ogricê}
{305}{}{I tak najlepiej wspominam nasze wspólne wypady do Z³omowa}

{350}{}{Kurwa, niech no se przypomnê nasze wspólne wypady tu w Cieniste Piaski}
{351}{}{Tu te¿ by³a taka szmira}
{352}{}{Nawet raz j¹ zawinêliœmy, ale ci st¹d dobrze zap³acili}
{353}{}{A ju¿ mieliœmy siê za ni¹ zabieraæ}

{400}{}{Kiedyœ to by³o}
{401}{}{Teraz to ju¿ nie ma}

{450}{}{Widzieliœcie kiedyœ supermutanta?}
{451}{}{Nie?}
{452}{}{To teraz wyobraŸcie sobie mieszankê Matta, takiego przeroœniêtego Matta tylko jeszcze brzydszy i pomalowany na zielono}
{453}{}{To rzeczywiœcie okropny.}

{500}{}{:bek:} #no beka po prostu

{550}{}{Ale mnie jeb³o}

{600}{}{S³odziutkie to piwko. Nie za gorzkie takie.}