{50}{}{Wszystko stracone...}
{51}{}{Wszyscy nie ¿yj¹...}
{52}{}{Po prostu pójdŸmy w swoje strony...}

#Tycho vs Isaac
{100}{}{Plan siê powiód³ w stu procentach, co za ulga...}
{101}{}{Rebelianci!}
{102}{}{Jestem Tycho, Stra¿nik Pustkowii!}
{103}{}{To ja wam przerzuca³em broñ przez mur!}
{104}{}{Nie jesteœcie nam nic winni.}
{105}{}{O œwicie wyruszamy w stronê Krypty 15.}
{106}{}{Znajdziecie tam schronienie oraz nowy start.}
{107}{}{Nie bêdê mia³ ¿alu, jeœli odrzucicie moj¹ propozycjê.}
{108}{}{WeŸcie wszystko, co potrzebne, bo za godzinê wyruszamy.}
{109}{}{Bêdê czeka³ na was pod g³ówn¹ bram¹.}

#Zamiast 102
{110}{}{Jesteœmy Stra¿nikami Pustkowi i pomogliœmy wam w ucieczce!} #104, 105, 106, 107, 108, 109

{115}{}{Najpierw rozprawimy siê ze zdrajcami!}
{116}{}{Isaac... daj spokój...}
{117}{}{Z kim?!}
{118}{}{Osobiœcie zapakujê kulkê w ³eb ka¿demu, kto w obozie wspó³pracowa³ z Chanami!}

{120}{}{Osobiœcie to ja ciebie mogê skasowaæ, nawet zaraz.}
{121}{}{Nikt ju¿ nie zginie z niczyjej rêki pod moj¹ obecnoœci¹.}

{125}{}{Przyrzek³em sobie, ¿e jeœli prze¿yjê, wszyscy zaprzañcy dostan¹ to na co zas³u¿yli.}
{126}{}{Spierdalaj st¹d, Tycho!}

{130}{}{Nie mam zamiaru nigdzie siê ruszaæ.}
{131}{}{To koniec rozlewu krwi.}

{135}{}{Wiesz co?}
{136}{}{Mam nadziejê, ¿e ten jeden bêdzie celny!}

{140}{}{Zwariowa³!}

#Alternative
{150}{}{Mamy przewagê liczebn¹ Isaac. Zginiesz tylko ty i nici z twojej zemsty.}
{151}{}{Za skuteczne u¿ycie umiejêtnoœci retoryki zdobywasz 200 PD.}

{160}{}{Pierdolcie siê wszyscy.}
{161}{}{ZejdŸcie mi z drogi.}
{162}{}{Niech tê wasz¹ kryptê szlag trafi.}

#Non-Alternative
{170}{}{Wyruszamy za godzinê.}
{171}{}{Wiecie gdzie mnie szukaæ.}

#Oswald
{200}{}{Oswald, ty pieprzona, œmierdz¹ca kupo gówna...}
{201}{}{Teraz wyrównamy rachunki.}
{202}{}{Ahhh…}
{203}{}{S³usznie podejrzewa³em, ¿e coœ knu³eœ.}
{204}{}{Darujmy sobie te uprzejmoœci.}
{205}{}{IIIJAAAAAHAAAA}

#Campdoor
{230}{}{Bierz dupê w troki i zostaw te drzwi!}

#Meeting Garl
{300}{}{Nastêpni?}
{301}{}{Wiêcej was matka nie mia³a?}
{302}{}{Jedno mnie zastanawia.}
{303}{}{Sprz¹tniêcie was bêdzie jak skinienie palcem dla mnie.}
{304}{}{Wiêc po co wam to wszystko?!}
{305}{}{I tak sobie nie daracie rady na pustkowiach.}
{306}{}{Chcemy umrzeæ jako wolni ludzie!} #20069
{307}{}{Daruj sobie to romantyczne gówno}
{308}{}{Bez was te¿ sobie poradzimy} #wyjmuje broñ

#Khans running out
{320}{}{Co to kurwa mia³o byæ.}
{321}{}{Wy bando imbecyli!}
{322}{}{Nawet nie wiecie jak mam teraz was ochotê zajebiœcie rozpierdoliæ!}
{325}{}{CZEKAJCIE!!!}
{326}{}{GARL  N I E  ¯ Y J E!}
{327}{}{TO NIE MA SENSU!}
{328}{}{JA SIÊ ZMYWAM!!!}
{329}{}{Pieprzyæ to.}
{330}{}{IDIOCI, STAÆ!!!}
#Odwraca sie do graczy i nagle fuck it
{331}{}{Jeszcze siê zobaczymy!}
{332}{}{To ten...}
{333}{}{Czas na mnie.}

#After Garl Death
{350}{}{Czekaj!}
{351}{}{Tak?}
{352}{}{A co ze zdrajcami, którzy weszli w uk³ady z Chanami?}
{353}{}{Mówiê na przyk³ad o tym pieprzonym sklepikarzu i o cholernych bimbrownikach.}
{354}{}{Oni wszyscy wydostali siê z obozu podpierdalactwem!}
{355}{}{Trzeba wymierzyæ im sprawiedliwoœæ.}
{356}{}{Nie, to ju¿ koniec.}
{357}{}{¯aden strza³ ju¿ nie padnie.}
{358}{}{Wiêc schowaj lepiej tê broñ.}
{359}{}{Ty myœlisz, ¿e bêdziesz za nas decydowa³, bo nam dawa³eœ broñ?}
{360}{}{Myœlê, ¿e wszyscy dooko³a chc¹ ju¿ spokoju.}
{361}{}{Ha! To zobaczmy ile nas jest!}
{362}{}{No dalej!}
{363}{}{Wci¹¿ tylko ma³a garstka.}
{364}{}{Dobra.}
{365}{}{Ka¿dy komu w g³owie wiêcej ni¿ sieczka zapraszam za mnie.}
{366}{}{Ja nie ¿artujê, nawet gdybyœ ty mi mia³ stan¹æ na drodze!}
{367}{}{Wiem.}
{368}{}{Dlatego ka¿dy kto ma ju¿ tego doœæ, bêdzie bezpieczny za moimi plecami.}
{369}{}{Naprawdê nie wiem co by siê mia³o staæ, ¿ebym zmieni³ zdanie!}
{370}{}{A ja na pewno nie wystrzelê jako pierwszy.}
