{199}{}{Znowu ty? Chcesz do œrodka, czy co?}
{200}{}{Hej, frajer, chcesz trafiæ do pierdla? Hehe.}
{201}{}{Myœlisz, ¿e masz spluwê i taki kozak jesteœ?} #Retoryka
{202}{}{Nie chcê.}
{203}{}{Chcê.}
{204}{}{Pójdê ju¿.}

{210}{}{Ooo patrz jaki wygadany. Zobaczymy, czy te¿ bêdzie tak gwizda³ po drugiej stronie siatki… [Stra¿nicy wyci¹gaj¹ pa³ki i powolnym krokiem zmierzaj¹ w twoj¹ stronê.]}
{211}{}{[Nic nie rób.]}
{212}{}{[Broñ siê.]}

{220}{}{Tak jak myœla³em. Zabieraj swój g³adziutki ty³eczek w troki i zje¿d¿aj st¹d, albo porozmawiamy sobie jak Pan i s³uga. Pierwsze skrzypce bêdê gra³ ja, naturalnie.}
{221}{}{Dobra...}