{200}{}{Witaj. Jestem Ethan, chyba nie by³o mi dane widzieæ ciê tu wczeœniej. Zgadujê, ¿e jesteœ tu od niedawna.}
{201}{}{Kim jesteœ?}
{202}{}{Wybacz, mia³em ciê za kogoœ innego... pójdê ju¿.}

{210}{}{Kiedyœ nale¿a³em do policji du¿ego miasta na po³udnie st¹d. Kiedy supermutanci weszli do miasta, wszyscy zaczêli uciekaæ w pop³ochu we wszystkie strony. Stawialiœmy opór, ale nie mia³o to wiêkszego sensu. Mutanci dos³ownie rozgromili nasze oddzia³y, nie oszczêdzali nikogo. By³em bardziej wspania³omyœlny ni¿ moi kompani i nie anga¿owa³em siê w walkê tak jak oni. Nazwij mnie tchórzem, wyjebane. Nie ut³ukli ¿adnego skurwiela, a ja przynajmniej oszczêdzi³em swoj¹ dupê. ¯al mi tylko tych wszystkich g³upców, którzy poszli na pierwszy ogieñ...}
{211}{}{...A to miejsce? Jak tutaj trafi³eœ?}

{220}{}{No chwila, jeszcze nie skoñczy³em. Jako, ¿e wszystko co mia³em i zna³em obróci³o siê w niwecz, nie mia³em co ze sob¹ zrobiæ, wiêc ruszy³em przed siebie, na pó³noc, a¿ trafi³em tutaj.}
{221}{}{Jak d³ugo tutaj jesteœ?}

{230}{}{Uch… nie wiem. Straci³em tutaj totalnie rachubê czasu. Przepijam resztkê kapsli, a potem... potem siê zobaczy. A jaka jest twoja historia?}
{231}{}{Nie twój interes.}
{232}{}{Pochodzê z krypty na wschód st¹d. Cudem paru nam uda³o mi siê uciec hordzie supermutantów. Zbieram ekipê do odbicia moich pobratymców. Chcesz siê przy³¹czyæ?}

{240}{}{To by³o bardzo niegrzeczne z twojej strony. Wybacz… ale nie mam zamiaru marnowaæ na ciebie wiêcej czasu.}
{241}{}{[KONIEC]}
{242}{}{Nie mam ci nic wiêcej do powiedzenia.}
{243}{}{Nie bêdê wiêcej z tob¹ rozmawia³.}
{244}{}{Wykorzysta³eœ ju¿ mój kredyt zaufania. OdejdŸ.}

{250}{}{Rozumiem twoj¹ sytuacjê. Mi te¿ by³o na pocz¹tku trudno pogodziæ siê z utrat¹ przyjació³, ale w przeciwieñstwie do ciebie nie podejmowa³em tak radykalnych kroków, bo to czysta g³upota. Ale nie bêdê ci psu³ zabawy. Skoro podchodzisz do tego serio, to spróbuj jakoœ wyci¹gn¹æ z obozu kolesia o tym samym fikuœnym stroju co ty. We dwójkê byœcie brzmieli bardziej przekonywuj¹co.}
{251}{}{Kogo?!}
{252}{}{Hmm... to dobry pomys³. Dziêki!}

{260}{}{Zaczekaj! Zanim odejdziesz, móg³byœ mi odpowiedzieæ na jedno proste pytanie?}
{261}{}{Œmia³o, wal.}
{262}{}{Wybacz, mam wa¿niejsze sprawy na g³owie.}
{263}{}{Witaj ponownie, bracie. Czy nie chcia³byœ mi mo¿e odpowiedzieæ na pewne filozoficzne pytanie?}

{270}{}{Gdybyœ mia³ woln¹ rêkê... prze¿yæ wspania³¹ przygodê... porzuciæ swe troski... w któr¹ stronê Œwiata wybra³byœ siê?}
{271}{}{Na po³udnie.}
{272}{}{Na wschód.}
{273}{}{Na zachód.}
{274}{}{Na pó³noc.}
{275}{}{Hmm... a inny kierunek ni¿ po³udnie?}
{276}{}{Interesuj¹ce... Dziêki, przyjacielu. Mam nadziejê, ¿e siê jeszcze spotkamy.}
{277}{}{Bywaj.}

{280}{}{No… wygl¹da³ na niezbyt skalanego inteligencj¹, ale za to sprawia³ wra¿enie takiego, co potrafi dobrze komuœ wywin¹æ. Ch³opaki musieli w kilku go trzymaæ, jeden nawet wskoczy³ mu na plecy [Œmieje siê] bo inaczej nie sz³o goœcia ogarn¹æ. Potem wrzucili go do obozu, no i pewnie wci¹¿ tam jest, o ile jeszcze nie wywali³ g³ow¹ dziury w murze i nawia³.}
{281}{}{Dlaczego go tam wtr¹cili?}

{290}{}{Nie wiem. Jakbyœ dotar³ do niego, móg³byœ go póŸniej o to zapytaæ. Chocia¿ bêdzie z tym  problem - goœciu ma pokaŸn¹ ranê na szyi. Nie wydusi z siebie ani s³owa.}
{291}{}{Hmm, to interesuj¹ce. Dziêki. Pójdê go odszukaæ.}

{300}{}{Jak chcesz zagadaæ, to wysil siê i podejdŸ. Nie bêdê przecie¿ nikogo tutaj przekrzykiwa³.}

{400}{}{Dobrze ciê widzieæ, przyjacielu.}
{401}{}{Co tam s³ychaæ, kolego?}
{402}{}{Powoli koñcz¹ mi siê kapsle.}

{1000}{}{Za wskazanie Ethanowi drogi zyskujesz 100 puntków doœwiadczenia.}