{200}{}{A teraz drogie dzieci s³uchajcie, bo byæ mo¿e moje nauki siê wam kiedyœ przydadz¹.}
{201}{}{W³ócznia to jedna z najstarszych znanych broni na Œwiecie.}
{202}{}{Wymyœlono j¹ tak dawno, ¿e nawet Staro¿ytni nazywali jej twórców staro¿ytnymi.}
{203}{}{Cofnijmy siê na chwilê do tych czasów.}
{204}{}{Dowiedzmy siê dlaczego coœ takiego jak w³ócznia w ogóle powsta³o.}
{205}{}{Je¿eli zg³êbimy genezê tego niesamowitego przedmiotu dowiemy siê jak siê nim pos³ugiwaæ.}
{206}{}{Otó¿ moi drodzy wyobraŸcie sobie tak¹ sytuacjê.}
{207}{}{W wasz¹ stronê z ogromn¹ prêdkoœci¹ zbli¿a siê wyg³odnia³y kojot, ucieczka nie wchodzi w rachubê.}
{208}{}{Co robicie?}
{209}{}{Rzucacie siê w jego stronê, czy mo¿e próbujecie unikn¹æ pierwszego uderzenia?}
{210}{}{Ja nie wiem.}
{211}{}{Nigdy siê te¿ nie zastanawia³em.}
{212}{}{Natomiast kiedy trzymacie w rêku w³óczniê wystarczy nakierowaæ grot w stronê przeciwnika.}
{213}{}{Si³a z któr¹ zwierz nadzieje siê na w³óczniê jest niewyobra¿alna.} # 1
{214}{}{To jest dopiero niez³a iguana na patyku!}
{215}{}{To samo sta³oby siê z ka¿d¹ dowoln¹ istot¹, czyli tak¿e cz³owiekiem.}
{216}{}{Otó¿ moje dzieci nie ma broni bia³ej lepszej ni¿ w³ócznia.}
{217}{}{Zasiêg na który pozwala powoduje, ¿e ka¿da inna broñ bia³a oprócz ciê¿kich m³otów jest przy niej bezu¿yteczna.} # 1
{218}{}{M³ot w przeciwieñstwie do w³óczni wymaga czêsto pracy obu r¹k, a w³ócznia jest lekka i mobilna.}# 1
{219}{}{Zadaniem m³ota jest mia¿d¿yæ, w³óczni przebijaæ.} # 1
{220}{}{To drugie okazuje siê byæ znacznie skuteczniejsze od pierwszego.}
{221}{}{Oczywiœcie zwyk³e trzymanie w³óczni nigdy nie jest efektywne.}
{222}{}{Wbijajcie j¹ zawsze do samego koñca.}# 1
{223}{}{Waszym zadaniem nie jest zraniæ przeciwnika, a zadaæ koñcowy cios.} #1
{224}{}{Poproszê teraz moj¹ córkê Tamarê, ¿eby coœ zademonstrowaæ.}

{225}{}{Kochanie, jeœli pozwolisz.}
{226}{}{Tamara nosi p³ytowy pancerz, a grot mojej dzidy jest celowo stêpiony dla bezpieczeñstwa mojej córki.}
{227}{}{Czasami, gdy trudno wycelowaæ w serce, a przeciwnik nosi ciê¿ki pancerz mo¿emy go powaliæ.}
{228}{}{Im wy¿ej celujecie tym lepiej, wróg ³atwiej traci równowagê.} # 1
{229}{}{Oto i efekt.}
{230}{}{Na dzisiaj to tyle.}
{231}{}{Jeœli jesteœcie zainteresowani wykupieniem dziennego szkolenia to proszê bardzo.}
{232}{}{200 kapsli od ³ebka.}
{233}{}{Dziêkujê za uwagê.}

{250}{}{Zyskujesz 2 dodatkowe punkty umiejêtnoœci broni bia³ych.}