{200}{}{IdŸ odpracuj swoj¹ dzisiejsz¹ dzia³kê, potem wróæ do nas. Musimy porozmawiaæ.}

#FirstTalk

{210}{}{Witaj nieznajomy. Nie widzia³em ciê tu wczeœniej, musisz odpowiedzieæ nam na jedno zasadnicze pytanie. Masz zamiar st¹d uciec?}
{211}{}{Tak.}
{212}{}{Co jeœli powiem nie?}

{220}{}{To by oznacza³o, ¿e albo postrada³eœ zmys³y, albo po prostu chcesz siê przypodobaæ Chanom. To jak? Jesteœ z nami, czy przeciw nam?}
{221}{}{Trzymam z wami.}
{222}{}{Bêdê sta³ z boku.}

{230}{}{Nie ma czegoœ takiego jak stanie z boku. Zobaczysz… jeszcze dzisiaj zmienisz zdanie i wrócisz, zaufaj mi.}
{231}{}{Taaa…}
{232}{}{Jestem z wami, o co chodzi?}

{240}{}{Œwietnie! W nocy organizujemy naradê. Jesteœ nowy, chcemy unikn¹æ nieprzyjemnoœci, wiêc nie powiemy ci gdzie siê ona odbêdzie. Pójdziesz tam z nami. Tylko powiedz kiedy bêdziesz gotowy.}
{241}{}{Móg³bym iœæ nawet teraz. [Zaczekaj do wieczora.]}
{242}{}{W porz¹dku, wrócê kiedy bêdê gotowy.}
{243}{}{Mam kilka pytañ.}
{244}{}{Wrócê póŸniej.}
{245}{}{Przemyci³em radio do obozu. Jest ktoœ kto chce z wami rozmawiaæ! [Poka¿ radio.]}

{250}{}{Na litoœæ bosk¹, schowaj to! Nie teraz, gdy stra¿nicy patrz¹! Zachowaj to na wieczór.}
{251}{}{Dobra, ju¿ dobra.}

{300}{}{O co chodzi?}
{301}{}{Jestem gotowy na naradê [Poczekaj do wieczora.]}
#243
#244

{310}{}{Witaj ponownie, czy zmieni³eœ swoje zdanie?}
#232
#244

#Questions
{500}{}{Kto pyta nie b³¹dzi. O co chodzi?}
{501}{}{Jak siê tu znaleŸliœcie?}
{502}{}{Szukam Tandi.}
{503}{}{Kim s¹ ci ludzie, którzy nas przetrzymuj¹?}
{511}{}{Jak myœlisz co siê sta³o z ludŸmi, którzy tu niegdyœ mieszkali?}
{512}{}{Gdzie le¿y Hub?}
{504}{}{To chyba tyle pytañ na teraz. Wrócê na naradê.}

{510}{}{Jestem jednym z tych, którzy przybyli tu jako pierwsi. Handlowa³em tu i tam, ale tutaj by³em sta³ym bywalcem. Za rzeczy, które kupowa³em w Hub przep³acali jak cholera. Biznes kwit³, a¿ jednego dnia przybywam z rzeczami, a tu wita mnie banda zwana Chanami, po starych mieszkañcach ani œladu, musieli opuœciæ to miejsce tu¿ przed ich przybyciem. O dalszej czêœci przekona³eœ siê na w³asnej skórze. No a potem jak ludzi przybywa³o, to i w obozie ludzi przybywa³o.}
{520}{}{Nie mam bladego pojêcia. Podró¿e z Hub trwa³y bardzo d³ugo, du¿o rzeczy mog³o siê pozmieniaæ w tak d³ugim przedziale czasowym. Ale wiem jedno, nie widzê tutaj, ani jednej duszy, która tutaj wczeœniej mieszka³a.}
{530}{}{Bardzo daleko na po³udniu, a raczej to co z niego zosta³o. Dochodz¹ mnie s³uchy, nawet tutaj, ¿e supermutanci najechali miasto i doszczêtnie je zniszczyli. Mo¿e dobrze, ¿e mnie tam wtedy nie by³o…}
{540}{}{Obi³o mi siê kiedyœ to imiê o uszy. Ba! Nawet j¹ widzia³em, to córka Aradesha - dawnego przywódcy tej wioski. Tutaj jej nie znajdziesz, a ja nie mam pojêcia, gdzie jej szukaæ. Wybacz.}
{550}{}{To Chanowie, banda zbirów z pustynii. Kiedyœ siedzieli w pewnym magazynie i napadali na nieistniej¹ce dzisiaj Z³omowo, dzisiaj wynieœli siê tutaj. S¹ jak hieny, które ¿eruj¹ na tym co pozosta³o. Ciekawe co zrobi¹ gdy ju¿ opuœcimy to miejsce.}

{900}{}{Wszyscy ju¿ s¹?}
{901}{}{Nie widzê Jerome’a. Gdzie jest Jerome?}
{902}{}{Dobra, obejdziemy siê bez niego.}
{903}{}{Przemyœla³em ca³¹ sprawê.}
{904}{}{S³uchajcie!}
{905}{}{Jak niektórzy z was wiedz¹, w sk³adziku za nami jest broñ.}
{906}{}{Ktoœ nam j¹ codziennie, sukcesywnie przerzuca³.}
#fadeout
{910}{}{Dlatego tej nocy, bierzemy sprawy w nasze rêce!}
{911}{}{Chyba, ¿e ktoœ ma lepszy pomys³, ale szybciutko proszê, bo zemsta nie mo¿e czekaæ.}

{920}{}{Jest coœ o czym powinniœcie wiedzieæ.}
{921}{}{A co to takiego?} #If not told about radio
{922}{}{Ach, tak. By³bym zapomnia³.}

{923}{}{Mam ze sob¹ radio}
{924}{}{Wygl¹da na to, ¿e znam osobê, która wam dostarcza³ broñ}
{925}{}{I jestem tutaj po to, ¿eby teraz miêdzy wami nawi¹zaæ ³¹cznoœæ} #Do2000

#Lina
{930}{}{Mam ze sob¹ linê dziêki której przedostaniemy siê na drug¹ stronê muru.}
{931}{}{Oprócz tego mam radio i ³¹cznoœæ z osob¹, która nas zabierze w bezpieczne miejsce.}
{935}{}{Hmmm...}
{936}{}{Isaac, no weŸ. Zróbmy jak ten goœæ mówi, no.}
{937}{}{To jedyna rozs¹dna opcja.}
{938}{}{Cholera... Myœla³em, ¿e siê odwdziêczymy piêknym za nadobne.}
{939}{}{Ale i mo¿e macie racjê.}
{940}{}{Powiedz temu komuœ, ¿e wchodzimy w to.}
{941}{}{Dobra.}
{942}{}{Mia³em wywo³anie, co jest? Odbiór.}
{943}{}{Jesteœmy gotowi.}
{944}{}{Teraz? Cholera...}
{945}{}{Dobra.}
{946}{}{Ustawcie siê pod pó³nocn¹ œcian¹.}
{947}{}{Bêdê do dwóch minut.} #fadeout
{948}{}{Pojedynczo, nie róbcie zbytniego ha³asu.}
{949}{}{Ilu was tam jeszcze zosta³o?}
{950}{}{Paru.}
{951}{}{Ruszajcie za mn¹, musimy siê jak najszybciej oddaliæ}

#Dynamit 960-990

{1000}{}{Wszyscy ju¿ s¹?}
{1001}{}{Nie widzê Jerome’a. Gdzie jest Jerome?}
{1002}{}{Dobra, obejdziemy siê bez niego.}
{1003}{}{S³uchajcie, przemyœleliœmy ju¿ ca³¹ sprawê.}

{1055}{}{Moment...}
{1056}{}{Ktoœ jest na zewn¹trz, hodu do kantorka! Biegiem!}
{1100}{}{No i? I gdzie niby jest kurwa to spotkanie, o którym mówi³eœ?}
{1101}{}{Czekajcie, to na pewno siê da jakoœ wyjaœniæ...}
{1102}{}{Gówno mnie obchodz¹ twoje wyjaœnienia.}
{1103}{}{I tak nie by³o z ciebie wiêkszego po¿ytku!}

{1104}{}{Dobra, nic tu po nas.}
{1105}{}{Marius zaczekaj...}
{1106}{}{???}
{1107}{}{I co?}
{1108}{}{Ciemno jak w dupie u...}
{1109}{}{Co to by³o?!}
{1110}{}{Co?}
{1111}{}{Aaarghh...}
{1112}{}{Skurwysynu, co zrobi³eœ z Szych¹!}
{1113}{}{Zap³acicie mi za to!}

{1115}{}{Ognia!!!}

{2000}{}{Z tej strony }
{2001}{}{, odbiór}
{2002}{}{S³yszê ciê }
{2003}{}{, jak sytuacja?}
{2010}{}{Witaj G³osie}
{2011}{}{Kto tam?}
{2012}{}{Jestem Isaac, formalny przywódca obozowej spo³ecznoœci}
{2013}{}{Witaj Isaac, co zrobiliœcie z broni¹, któr¹ wam dawa³em?}
{2014}{}{Schowaliœmy j¹ w bezpiecznym miejscu}
{2015}{}{Mamy j¹ pod rêk¹}
{2016}{}{Œwietnie}
{2017}{}{W najbli¿szym czasie...}

#Tylko o Tycho

#Po ataku w szopie
{2050}{}{Nie chcia³em takiego obrotu zdarzeñ. Z drugiej jednak strony mamy dwóch z g³owy. A nawet… trzech. Cieszy mnie, ¿e taki los spotka³ tego zdrajcy.}
{2051}{}{Co teraz zrobimy?}
{2052}{}{Du¿o mieliœcie zaprzañstwa w obozie?}

{2055}{}{Za du¿o. Wiêkszoœæ s³ugusów w czêœci zachodniej to byli donosiciele. Z nimi te¿ zrobimy porz¹dek, zaraz po Chanach.}
{2056}{}{Zaraz, zaraz. Co chcesz z nimi zrobiæ?}

{2057}{}{To samo, co oni zrobili z Jerome. Nie zas³uguj¹ na nic lepszego.}
{2058}{}{Ale to oznacza masakrê…}

{2060}{}{Nie mam czasu na dyskusje. }
{2065}{}{Póki Chanowie siê nie zorganizowali zajmiemy siê Oswaldem. Sukinsyn pewnie siê spodziewa do czego tu dosz³o. Nie powinniœmy d³u¿ej zwlekaæ.}
{2066}{}{Racja. ChodŸmy.}
{2067}{}{Poczekaj chwilê. Muszê siê zreorganizowaæ.}
{2068}{}{Nie ma czasu do stracenia.}

{2070}{}{To co? Mo¿emy ju¿ iœæ, czekamy ju¿ tylko na ciebie.}

{2098}{}{Nie ma lekko, padamy jak muchy. Musimy iœæ dalej, bo jak coœ siê zaczyna, to trzeba te¿ to skoñczyæ.}
{2099}{}{Cholera, straciliœmy naszego przyjaciela... Ale taka jest cena wolnoœci.}
{2100}{}{Cholera, to by³o ³atwiejsze ni¿ myœla³em. Oni padaj¹ jak muchy, a my wci¹¿ siê trzymamy w kupie.}
{2101}{}{Wiêc co robimy teraz?}

{2110}{}{Musimy znaleŸæ klucz do bramy obozu, na pewno ktoœ z nich go mia³, a jak nie to musz¹ go trzymaæ gdzieœ w tym budynku.}
{2111}{}{Pójdê go poszukaæ. Zaraz wracam.}

{2120}{}{Znalaz³eœ ju¿ ten klucz?}
{2121}{}{Jeszcze nie.}
{2122}{}{A, znalaz³em.}
{2123}{}{Pospiesz siê, proszê. Czas ucieka, wolnoœæ czeka.}

{3333}{}{[Musisz siê odpowiedŸ po jednej ze stron.]}
{3334}{}{Nie wiem jak ty, ale ja trzymam siê z Tycho.}
{3336}{}{Isaac, ty jebany idioto. Mo¿e dobrze strzelasz, ale z myœleniem to ty jesteœ na bakier. To, ¿e uda³o siê nam wydostaæ stamt¹d to jest NASZ WSPÓLNY SUCKES i nie zabronisz nam samym zadecydowaæ co zrobimy. Ja trzymam z Tycho, kto z nami?}

{3400}{}{Co... ty?! Wynoœ mi siê z widoku. Nie widzisz, ¿e mam problem przed sob¹ do rozwi¹zania?!}
{3401}{}{Trzymam z tob¹ Isaac.}
{3402}{}{Isaac, wiêkszoœæ nas przesz³a na stronê Tycho. Zawiedziesz nas wszystkich, jeœli w tamt¹ stronê padn¹ strza³y.}
{3405}{}{Czekaj...}

{3408}{}{Dziêki, z pewnoœci¹ kiedyœ ci wynagrodzê lojalnoœæ.}
{3409}{}{Spoko.}

{3410}{}{Na nich te¿ przyjdzie czas.}
{3411}{}{Kiedy? Spójrz, zginiesz od strza³ów jak pies, a w ich oczach ju¿ jesteœ jako wariat. Zaufaj mi, jeœli teraz od³o¿ysz broñ to potraktuj¹ to jako chwilowy przyp³yw gniewu.}
{3412}{}{Cholera... niech mnie szlag... dobra, masz racjê... czekaj.}
{3413}{}{[Czekaj.]}

#Tycho
{3420}{}{Streszczaj siê, mamy piek¹cy problem przed nami.}
{3421}{}{On ma racjê, Tycho, musimy pozbyæ siê ³ajdaków, którzy tu pozostali.}
{3422}{}{Trzymam z wami, Tycho.}

{3430}{}{Coooo?! Ty te¿ zwiariowa³eœ? S³uchaj, nie jesteœ w stanie nas przekonaæ. By³y pewne za³o¿enia zanim tutaj przybyliœmy na co sobie pozwolimy, a do czego nie dopuœcimy.}
{3431}{}{Dobra. Zatem trzymam z wami.}
{3432}{}{Czekaj...}
{3433}{}{Nie ma sensu tego przed³u¿aæ. Trzymam z Isaaciem.}

{3440}{}{Œwietnie, cieszê siê, ¿e nie uleg³eœ i wybra³eœ w³aœciwie. Stañ z boku. Ten wariat mo¿e lada chwila zaatakowaæ.}
{3441}{}{OK.}

{3450}{}{G³upio postêpujesz i zaraz bêdziesz tego ¿a³owa³... trudno.}
{3451}{}{[OdejdŸ.]}