#######################
#VAULT SUIT START ZONE#
#######################

{199}{}{O to ty... mi³ego dnia}

{200}{}{Hej... uhh... od dawna nosisz kombinezon krypty 13?}
{201}{}{Od zawsze, bo tam siê urodzi³em, dlaczego pytasz?} #250
{202}{}{A oskuba³em jakiegoœ frajera z tego œmiesznego kostiumu.} # INT >=6
{203}{}{Sprzeda³ mi go pewien handlarz z zachodu.} 

### Player not from vault
{210}{}{Aaa to w porz¹dku, a wiesz mo¿e gdzie le¿y ta krypta?}
{211}{}{Mówi³em ju¿, ¿e to nie mój kostium. Nie wiem gdzie jest ta krypta.}
{212}{}{A wiem.}

{220}{}{To siê œwietnie sk³ada, bo mia³bym dla ciebie robotê.}
{221}{}{A to szkoda, ale móg³bym mieæ dla ciebie robotê.}
{222}{}{Co to za praca?}
{223}{}{Nie interesuje mnie to.}

{230}{}{W porz¹dku, gdybyœ coœ chcia³ zawsze mo¿esz mnie tu znaleŸæ.}
{231}{}{Bêdê wiedzia³.}

### Player from vault
{250}{}{A nie nic... tylko... kiedyœ przeczyta³em, ¿e ludzie z krypt s¹ bardziej podatni na choroby z którymi my mieszkañcy pustkowii spotykamy siê na codzieñ. S³uchaj, mamy dobry sprzêt diagnostyczny, badanie zajê³oby mniej ni¿ dwie godziny. To jak?}
{251}{}{Ale tak za darmo?}
{252}{}{Jasna sprawa! Gdzie mam siê rozsi¹œæ?}
{253}{}{Nie, dziêki. Mo¿e innym razem.}

{260}{}{Naturalnie. Wszelkie podziêki sk³adaj Garlowi - cz³owiekowi, który trzêsie tym miejscem. To robimy zabieee.. to znaczy diagnostykê?}
#252
#253

{270}{}{Szanujê twoj¹ wolê przybyszu z krypty, ale pamiêtaj, ¿e nic ciebie to nie kosztuje, a ca³y zabieg jest bezbolesny.}
{271}{}{W porz¹dku. Ja po prostu nie chcê - jeszcze nie teraz. Chcesz mnie o coœ jeszcze zapytaæ?}

{280}{}{Tak, poza tym, dlaczego opuœci³eœ swoj¹ kryptê?}
{281}{}{Nie twój interes.}
{282}{}{Zaatakowali nas supermutanci.}

{290}{}{Aaa rozumiem. Wiesz co? Jest tam mój cz³owiek, Syriusz go nazywaj¹. Móg³byœ mu przekazaæ ten holodysk? Od jakiegoœ ju¿ czasu... uch... rozpracowujemy t¹ grupê. Zas³u¿byœ siê nie doœæ, ¿e nam to jeszcze przyjacio³om z krypty.}
{291}{}{Hmmm, chyba mo¿na ci zaufaæ. Ale wiesz, ¿e muszê jakoœ omin¹æ hordy supermutantów, które tam na mnie czekaj¹?}
{292}{}{Chyba myœlisz, ¿e mam coœ z g³ow¹ jeœli siê zgodzê.}

### Being rude
{300}{}{Wybacz, ale twoja kultura osobista pozostawia wiele do ¿yczenia. Niestesty nie jestem w stanie rozmawiaæ z osob¹ twojego pokroju.}
{301}{}{Wiêc siê bujaj.}

{302}{}{Wynoœ siê!}

#Refuse Quest


#######################
#### BEFORE QUESTS ####
#######################

{305}{}{Szkoda mi tylko twoich przyjació³, ja na twoim miejscu zacz¹³bym robiæ cokolwiek, ¿eby ich ratowaæ.}
{306}{}{A ja na pewno nie zacz¹³bym tego od wspierania pomagierów supermutantów. Do widzenia.} #Node999

{310}{}{Nie podoba mi siê twój ton. Wróæ jak zmienisz zdanie.}
{311}{}{Nie wydaje mi siê.}

{335}{}{Masz zamiar w koñcu pomóc swoim pobratymcom?}
{336}{}{Niech ci bêdzie, mów o co chodzi.}
{337}{}{Wolê wsadziæ sobie w dupê lufê od miniguna ni¿ z wami siê zadawaæ. Do nie widzenia.}

{340}{}{To jak? Przychodzisz tym razem za prac¹?}
{341}{}{Co jest do zrobienia?}
{342}{}{Wpadnê kiedy indziej. Czeœæ!}

{345}{}{Wróc tu kiedy zmienisz zdanie. O kasple na pustkowiach dzisiaj ciê¿ko.}
{346}{}{Nie s¹dzê.}

{350}{}{Przemyœl to. Taka okazja nie trafi siê znowu szybko.}
{351}{}{Zobaczymy.}

{360}{}{I jak? Zmieni³eœ zdanie? O kapsle na pustkowiach dzisiaj ciê¿ko.}
{361}{}{By³o od razu mówiæ, ¿e chodzi o pieni¹dze. Mów co jest do zrobienia.}
{362}{}{Nie, nie zmieni³em i zdanie nie zmieniê.}

#######################
#VAULT SUIT HOLO QUEST#
#######################

###### MOWILEM JUZ ZE NIE WIEM

{400}{}{Oto holodysk, który musisz dostarczyæ do krypty sk¹d pochodzi twój kombinezon. Musisz tam te¿ znaleŸæ cz³owieka, którego nazywaj¹ Syriuszem i to jemu przeka¿esz ten holodysk. Jeszcze jedna bardzo wa¿na kwestia - liczê na pe³n¹ dyskrecjê, s³ono p³acê za t¹ robotê, wiêc nie spierdol tego synu.}
{401}{}{Oto holodysk, który musisz dostarczyæ do krypty sk¹d pochodzi twój kombinezon. Musisz tam te¿ znaleŸæ cz³owieka, którego nazywaj¹ Syriuszem i to jemu przeka¿esz ten holodysk. Jeszcze jedna bardzo wa¿na kwestia - liczê na pe³n¹ dyskrecjê, s³ono p³acê za t¹ robotê, wiêc nie spierdol tego córko.}
{402}{}{Co takiego jest na tym holodysku, ¿e prosisz o anonimowoœæ?}
{403}{}{Ale gdzie mam dok³adnie to zanieœæ!?}

{410}{}{Nic co powinno ciê zainteresowaæ, nie p³acê ci za gadanie. Poza tym i tak holodysk jest porz¹dnie zaszyfrowany, wiêc ka¿da próba odczytania go zakoñczy siê fiaskiem. Coœ jeszcze?}
#403

{420}{}{Sam nie wiem dobrze, ale kiedy studiowa³em mapy zauwa¿y³em pewn¹ zale¿noœæ. Ta krypta znajduje siê idealnie w linii prostej na zachód. Zrobisz to dla mnie? Proszê.}
{421}{}{Zobaczê co siê da z tym zrobiæ.}
{422}{}{Wiesz co? WsadŸ sobie w dupê ten holodysk. Jeœli nie potrafisz mi pomóc w udzieleniu podstawowych informacji to sam sobie go bêdziesz nosi³.}


{420}{}{Jest taka krypta w górach, sam nie mam pojêcia, gdzie siê dok³adnie znajduje. Ale za to wiem, ¿e jest ona dok³adnie na zachód st¹d. Aaaa i jeszcze jedno: weŸ te szaty i bez nich nie krêæ siê tam.}
{421}{}{No to ma teraz sens. To chyba tyle. Pójdê to zanieœæ.}
{422}{}{Wiesz co? Chyba bêdziesz musia³ znaleŸæ kogoœ innego do tej roboty.}

{430}{}{Wspaniale! Nie ma czasu do stracenia, idŸ ju¿.}
{431}{}{Dziêki, rozejrzê siê zanim wyruszê.}
{432}{}{Dziêki, wyruszam z miejsca.}

###### A WIEM 

{500}{}{Oto holodysk, który trzeba dostarczyæ do krypty o której mówi³eœ, ¿e znasz. Potem znaleŸæ cz³owieka, którego nazywaj¹ Syriuszem i przekazaæ mu ten holodysk. To sprawa miêdzy tob¹, mn¹, a Syriuszem. P³acê ci g³ównie za dyskrecjê.}
{501}{}{Oto holodysk, który trzeba dostarczyæ do krypty o której mówi³aœ, ¿e znasz. Potem znaleŸæ cz³owieka, którego nazywaj¹ Syriuszem i przekazaæ mu ten holodysk. To sprawa miêdzy tob¹, mn¹, a Syriuszem. P³acê ci g³ównie za dyskrecjê.}
{502}{}{Co takiego jest na tym holodysku, ¿e prosisz o anonimowoœæ?}
{503}{}{Czyli co? Wchodzê tam, zanoszê holodysk i... wychodzê?}

{510}{}{Nic co powinno ciê zainteresowaæ, nie p³acê ci za gadanie. Poza tym i tak holodysk jest porz¹dnie zaszyfrowany, wiêc ka¿da próba odczytania go zakoñczy siê fiaskiem. Coœ jeszcze?}
#503

{520}{}{No tak, przydadz¹ ci siê te szmaty, ¿eby ciê nikt nie poæwiartowa³ na dzieñ dobry.}
{521}{}{Uch... dobrze, ¿e to mówisz... TERAZ.}

{530}{}{To jak? Zrobisz to dla mnie? Proszê.}
{531}{}{No dobra. [WeŸ szmaty i holodysk]}
{532}{}{Zbyt du¿e ryzyko. 1500 kapsli i jesteœmy kwita.}

{540}{}{Niech ciê... no dobra. Niech bêdzie moja strata. Dam ci te 1500 kapsli.}
{541}{}{Dasz 2500 i wyruszam z miejsca. Inaczej nie podejmujê siê tego w ogóle.}
{542}{}{No dobra. [WeŸ szmaty i holodysk]}
{543}{}{Wiesz co? Chyba bêdziesz musia³ znaleŸæ kogoœ innego do tej roboty.}

{549}{}{Nie bêdzie wiêcej. Koniec kropka.}
{550}{}{No pewnie. W ¿yciu takiej sumy nie widzia³em. Wiesz, ¿e chciwy traci dwa razy? Za takie gierki nie dostaniesz wiêcej ni¿ 500 kapsli. Koniec dyskusji.}
{551}{}{No to ca³uj misia w pompkê.}
{552}{}{Cholera, niech ci bêdzie. [WeŸ holodysk i szmaty]}

{560}{}{Wspaniale! Nie ma czasu do stracenia, idŸ ju¿.}
{561}{}{Dziêki, rozejrzê siê zanim wyruszê.}
{562}{}{Dziêki, wyruszam z miejsca.}

{570}{}{Znowu ty? Mówi³em ju¿, 500 kapsli i zdania nie zmieniam.}
{571}{}{Niech ci bêdzie. [WeŸ holodysk i szmaty]}
{572}{}{Spadam st¹d.}


###### JESTEM Z TEJ KRYPTY DAWAJ SZATY

{600}{}{A no racja. ¯e te¿ wczeœniej o tym nie pomyœla³em.... Na pewno przydadz¹ ci siê te ³achy. Wystarczy, ¿e je za³o¿ysz, nikt nie bêdzie siê ciebie czepia³.}
{601}{}{Okej, a jak ten holodysk ma pomóc moim przyjacio³om?}
{602}{}{Wybacz, nie nadajê siê do tego, musisz znaleŸæ kogoœ innego do tego zadania.} # --> 305
{603}{}{W porz¹dku. Zaniosê ten holodysk. [WeŸ holodysk i szmaty]}

{610}{}{No wiesz... to zbyt skomplikowane na jedn¹ rozmowê. Wystarczy, ¿e to dostarczysz Syriuszowi, a w ten sposób do³o¿ysz jedn¹ ma³¹ cegie³kê ku œwietlanej przysz³oœci.} #bright future
#602
#603

{620}{}{Wspaniale! Nie ma czasu do stracenia, idŸ ju¿.}
{621}{}{Dziêki, rozejrzê siê zanim wyruszê.}
{622}{}{Dziêki, wyruszam z miejsca.}

#Reading holodisk - powiedzenie co siê o tym myœli
{700}{}{Uda³o mi siê odczytaæ holodysk. Wiem o wszystkim - o tym, co chcecie zrobiæ z tym miejscem i jego mieszkañcami. Idê z tym do Galahada, skurwysyny.}
{701}{}{Nigdzie nie pójdziesz...} # You won't go anywhere from here
{702}{}{Stra¿e! Pomocy! Bij¹ nas!}



#######################
#OTHER SUIT START ZONE#
#######################

{800}{}{Hej, nie wygl¹dasz na tutejszego.}
{801}{}{To dobrze zgadujesz.}
{802}{}{Naprawdê nie wygl¹dam?}

{810}{}{To œwietnie siê sk³ada, potrzebujê kogoœ takiego jak ty.}
{811}{}{Wal.}
{812}{}{Nie wydaje mi siê.}

{820}{}{No có¿. Gra jest warta œwieczki, ale jeœli na start przekreœlasz mnie to nie zas³ugujesz te¿ na moje kapsle.}
{821}{}{Trzeba by³o tak od razu, ¿e do gry wchodz¹ pieni¹dze. Do czego mnie potrzebujesz?}
{822}{}{I mo¿e masz racjê.}

{830}{}{Wybacz, pierwszy raz ciê tu widzê. No nic, ¿yczê mi³ego dnia.}
{831}{}{Wróc jak zmienisz zdanie}

{840}{}{Oto holodysk, który trzeba dostarczyæ krypty w górach na zachód st¹d. Nawet nie próbuj tego odczytywaæ, i tak jest zaszyfrowany jak cholera. Musisz znaleŸæ cz³owieka, którego nazywaj¹ Syriuszem. Liczy³bym od ciebie na pe³n¹ dyskrecjê, s³ono p³acê za to zadanie, wiêc nie spierdol tego synu.}
{841}{}{Oto holodysk, który trzeba dostarczyæ krypty w górach na zachód st¹d. Nawet nie próbuj tego odczytywaæ, i tak jest zaszyfrowany jak cholera. Musisz znaleŸæ cz³owieka, którego nazywaj¹ Syriuszem. Liczy³bym od ciebie na pe³n¹ dyskrecjê, s³ono p³acê za to zadanie, wiêc nie spierdol tego córko.}
{842}{}{Co takiego jest na tym holodysku, ¿e prosisz o anonimowoœæ?}
{843}{}{Ale gdzie mam dok³adnie to zanieœæ!?}

{850}{}{Nie p³acê ci za gadanie tylko za przesy³kê. Coœ jeszcze?}
#843

{860}{}{Jest taka krypta w górach, sam nie mam pojêcia gdzie siê dok³adnie znajduje. Ale za to wiem, ¿e jest ona dok³adnie na zachód st¹d. Aaaa i jeszcze jedno: weŸ te szaty i bez nich nie krêæ siê tam. No i oczywiœcie zap³acê ci za to.}
{861}{}{No to ma teraz sens. [WeŸ szmaty i holodysk] Pójdê to zanieœæ.}
{862}{}{Wiesz co? Chyba bêdziesz musia³ znaleŸæ kogoœ innego do tej roboty.}

{870}{}{Wspaniale! Nie ma czasu do stracenia, idŸ ju¿.}
{871}{}{Dziêki, rozejrzê siê zanim wyruszê.}
{872}{}{Dziêki, wyruszam z miejsca.}


{900}{}{Cieszê siê, ¿e jednak chcesz pomóc swoim przyjacio³om. W krypcie 13 jest mój cz³owiek, Syriusz go nazywaj¹. Móg³byœ mu przekazaæ ten holodysk? Od jakiegoœ ju¿ czasu... uch... rozpracowujemy t¹ grupê. Zas³u¿byœ siê nie doœæ, ¿e nam to jeszcze przyjacio³om z krypty.}





#######################
##### QUEST  ZONE #####
#######################

#Przed dostarczeniem
{1200}{}{Co tutaj jeszcze robisz, idŸ zanieœæ ten pieprzony holodysk!}
{1201}{}{[Sk³am] Zluzuj gacie staruszku, ju¿ go zanios³em.}
{1202}{}{Mo¿esz powtórzyæ komu mam zanieœæ ten holodysk?}
{1203}{}{W³aœnie siê za to zabieram i wpad³em siê tylko przywitaæ. Czeœæ.}
{1204}{}{[Sk³am] Zanios³em holodysk.}

{1210}{}{Ja pierdole, cz³owieku, do Syriusza, do kurwa Syriusza! Wypierdalaj st¹d, nie chcê ciê tu widzieæ z tym holodyskiem!}
{1211}{}{Dobra, ju¿ dobra.}

{1220}{}{No to ruszaj dupsko w tym momencie, ta sprawa nie mo¿e czekaæ.}
{1221}{}{Dobra.}

{1230}{}{No pewnie. W³aœnie co przed chwil¹ ci przekaza³em holodysk, a tu znowu tu jesteœ i mówisz mi, ¿e dostarczy³eœ. Kogo ty próbujesz oszukaæ?}
{1231}{}{Podró¿ st¹d tam trwa trzy, góra cztery dni. Wiêc nie próbuj mi opowiadaæ bzdur.} # reset quest time to 0
{1232}{}{Dobra, ju¿ idê.}

{1240}{}{No to co tutaj jescze robisz? Ruszaj swój zad!}


{1249}{}{Widzê, ¿e jesteœ tym razem w kombinezonie krypty. To znaczy, ¿e by³eœ tam, zarekwirowa³eœ sobie jedn¹ sztukê i dostarczy³eœ Syriuszowi holodysk. Czy siê mylê?}
{1250}{}{No i jak? Jakieœ wieœci?}
{1251}{}{Jeszcze siê z nim nie widzia³em.}
#1204
{1253}{}{Dostarczy³em holodysk.}


{1300}{}{Tak? I co Syriusz powiedzia³?}

{1302}{}{Odczyta³ holodysk, kaza³ tobie przekazaæ abyœ wraca³ oraz, ¿e czeka na ciebie nagroda.}                                   # True answer
{1303}{}{Powiedzia³ mi, ¿e nie móg³ siê doczekaæ wiadomoœci od ciebie i natychmiast odczyta³ holodysk.}   # Bad answer
{1304}{}{Powiedzia³ mi, ¿e jesteœ chorym sukinsynem i kaza³ mi zrobiæ z tob¹ na co zas³u¿y³eœ.}  # After read -> Fight
{1305}{}{Pomó¿cie! Chc¹ nas zabiæ!}

{1310}{}{Na prawdê tak powiedzia³? Ale przecie¿ tyle razy mnie ostrzega³ czym to grozi! Mo¿e... mo¿e moje informacje okaza³y siê na tyle przydatne, ¿e postanowi³ zamieœæ sprawê pod dywan?}
{1311}{}{Dobra, mam gdzieœ twoje smêty. Wyskakuj z kapsli. W ogóle co wy kombinujecie?}
{1312}{}{Swoje zrobi³em, jak to mia³o pomóc mieszkañcom mojej krypty?}

{1320}{}{Dobra, ju¿ dobra. To twoje piêæset.}
{1321}{}{Dziêki, bêdzie dla mnie jeszcze jakaœ robótka?}
{1322}{}{Hej, mia³o byæ TYSI¥C piêæset.} 

{1330}{}{No wiem, ale liczy³em na to, ¿e... uch... nie wrócisz stamt¹d w jednym kawa³ku.}
{1331}{}{Ale jestem tu i teraz, wiêc proszê ciê, nie wkurwiaj mnie tylko dawaj mi moj¹ nale¿noœæ!}
{1332}{}{W jednym kawa³ku, tak? Wiêc co ty na to, ¿e resztê moich kapsli wyci¹gnê z twoich kawa³ków?!} #Node998

{1340}{}{Dobra, spróbujmy za³atwiæ to inaczej. Zrobisz jeszcze coœ dla mnie, a ja ci zap³acê za to okr¹g³y tysi¹c. Zgoda?}
{1341}{}{Mo¿e byæ, byle ¿eby kapsle siê zgadza³y co do jednego!}
{1342}{}{A mo¿e wypruje pierw twoje flaki, a potem zabiorê swoj¹ dolê?} #Node998 
{1343}{}{Pieprzyæ ciebie i twoje kapsle. Wynoszê siê st¹d.} #Node999

{1350}{}{Co jak co, ale starego Jaspera to ty nie oszukasz. Ju¿ to widzê jak ten sukinsyn siê spodziewa³ wiadomoœci ode mnie. IdŸ mi st¹d i bez oddanego holodysku nie wracaj.}
{1351}{}{Niech tak bêdzie.}


{1360}{}{Dowiesz siê ju¿ nied³ugo, cierpliwoœci. Wy proœci ludzie zawsze chcecie wiedzieæ wszystko od razu.}
{1361}{}{Nie lubiê jak mówisz kluczem i uciekasz od tematu.}
{1362}{}{Móg³byœ mo¿e poratowaæ groszem?}

{1370}{}{Nic na to nie poradzê. Uwierz mi, to by³o warte zachodu.}
#1362

{1380}{}{A wiêc to tak starego ascetê chcesz wykorzystaæ?}
{1381}{}{Nie, nie zrozumia³eœ mnie, mia³em na myœli...}
{1382}{}{Nie po to ¿yciem ryzykujê, zeby potem ktoœ mnie...}

{1390}{}{ZAMKNIJ SIÊ... i daj nam siê spakowaæ, bo wkrótce wyruszamy do krypty 13. Bêdziesz móg³ sobie zabraæ st¹d to co zostanie, bo wszystkiego nie zdo³amy zabraæ.}
{1391}{}{No dobra... [Daj im robiæ swoje.]}
{1392}{}{Mam gdzieœ twoje gierki, zmywam siê st¹d.} #Node999

{1395}{}{W porz¹dku, wróc jak bêdziesz w lepszym nastroju.}
{1396}{}{Zobaczymy.}


{1800}{}{Uch. Widzê na tobie kombinezon krypty}
{1801}{}{Nie wspomina³em wczeœniej, ¿e jestem z tej krypty?}
{1802}{}{Nie wspomina³em wczeœniej, ¿e jestem z tej krypty? Ale to niewa¿ne, holodysk dostarczony i tak.}
{1803}{}{Najwidoczniej wzi¹³em sobie egzemplarzyk z krypty, której poda³eœ mi lokacjê.}
{1804}{}{Najwidoczniej wzi¹³em sobie egzemplarzyk z krypty, której poda³eœ mi lokacjê. Poza tym - tak jak prosi³eœ - dostarczy³em holodysk.}

{1810}{}{Nie... nie wspomina³eœ... S³uchaj, naprawdê nie potrzebujesz naszej po-pomocy? Mamy dobry sprzêt diagnostyczny - badanie zajmie góra dwie godziny.}
{1811}{}{No dobra.}
{1812}{}{Nie chcê.}

{1820}{}{A holodysk dostarczy³eœ?}
{1821}{}{Nie, mo¿esz powtórzyæ do kogo mia³em to zanieœæ?}

#######################
#####  FEV QUEST  #####
#######################

{2000}{}{Jest taka osoba w tej wiosce, Felix ma na imiê. Potrzebuje on pewnej kuracji w postaci zastrzyku. WeŸ to i idŸ prosto do niego, bêdzie opiera³ siê, ¿eby mu to wstrzykn¹æ, wiêc weŸ go z zaskoczenia.}
{2001}{}{I co dalej?}

{2010}{}{Odczekaj chwilê i zobaczysz jak mu siê od razu poprawia. [Uœmiecha siê.] Nooo... a potem wróæ, co nie?}
{2011}{}{Brzmi OK. Daj tê strzykawkê.}
{2012}{}{Co jest w tej strzykawce?}
{2013}{}{Nie zrobiê tego, ¿egnam.}

{2020}{}{Eee... mój w³asny specyfik, wzmocni to go, nie zaszkodzi.}
{2021}{}{Hmmm... interesuj¹ce.}

{2030}{}{To co zrobisz to dla mnie?}
{2031}{}{Mo¿esz powtórzyæ co jest do zrobienia?}

{2040}{}{Œwietnie! Mam nadziejê, ¿e nie zepsujesz tego. [Daje ci strzykawkê.]}
{2041}{}{[WeŸ strzykawkê.] Postaram siê.}

{2100}{}{I co? Zrobi³eœ to o co prosi³em?}
{2101}{}{Jeszcze nie.}
{2102}{}{Zrobi³em, a ty mnie oszuka³eœ, prawdopodobnie znowu. Dawaj kapsle, albo ciê sprzedam Galahadowi!}

{2110}{}{To pospiesz siê, proszê. To dla mnie wa¿na sprawa.}

{2120}{}{Nie rób nic g³upiego. Masz tu 2000 kaplsi i przestañ k³apaæ mord¹. Nigdy siê nie widzieliœmy.}
{2121}{}{[WeŸ kapsle.] I tu siê mylisz, wszyscy i tak dowiedz¹ siê o twojej przesz³oœci i czynach.}
{2122}{}{[WeŸ kapsle.] Rozumiemy siê.}
{2123}{}{Mam kilka pytañ.}

{2130}{}{¯adnych pytañ, ¿adnych odpowiedzi. OdejdŸ z kapslami, albo siê to Ÿle dla nas skoñczy. Nigdy siê nie widzieliœmy, rozumiemy siê?}

{2150}{}{Nie znam ciê, co tutaj robisz? OdejdŸ.}

#######################
####### CAPTURED ######
#######################

{9900}{}{Wspaniale! U³ó¿ siê tutaj wygodnie, podamy ci zaraz zastrzyk znieczulaj¹cy zanim przejdziemy do autop... operacji. [Wyjmuje zastrzyk z pomarañczow¹ ciecz¹ i wbija ci go z impetem w nogê. Wyjesz z bólu, a obraz przed oczyma zaczyna zanikaæ...]}
{9901}{}{Hej, mia³o byæ bez zastrzy... Auæ! [Odp³ywasz...]}

{9949}{}{[OK]}
{9950}{}{[Budzisz siê. Wydaje ci siê, ¿e minê³y wieki.]}

{9951}{}{Œwietna robota, doktorze Jasper. Na pewno Porucznik us³yszy o Pana wk³adzie w budowê Jednoœci}
{9952}{}{Och...}
{9953}{}{Jednak¿e za niesubordynacjê wzglêdem prze³o¿onych zostanie Pan ukarany najwy¿sz¹ form¹ kary bez wzglêdu na czynniki ³agodz¹ce}
{9954}{}{Pañskie zas³ugi bêd¹ zapisane w Ksiêdze Poœwiêcenia}

{9955}{}{Wykonaæ}
{9956}{}{Nie…}



{9970}{}{Ju¿ zaraz wstanie, poda³em mu œrodek wybudzaj¹cy}