### Mark - gate guard in Shady Sands ###

{10}{}{Za skuteczne u¿ycie umiejêtnoœci retoryki zdobywasz 100 PD.}
{11}{}{Pip-Boy's status updated.} #alternate global message #1
{21}{}{Witaj przybyszu w Cienistych Piaskach.}

{98}{}{W czym mogê ci jeszcze pomóc?}
{99}{}{Witaj ponownie. W czym mogê ci tym razem pomóc?}
{100}{}{Witaj przybyszu w Cienistych Piaskach, jedynej cywilizacji w tym rejonie. Zachowuj siê podczas pobytu i nie prowokuj stra¿ników.}

{101}{}{Co to za miejsce?}
{102}{}{Kim jesteœ?}
{103}{}{Szukam niejakiej Tandi, znajdê j¹ tutaj?}
{104}{}{Widzia³eœ moich przyjació³? Nosz¹ kombinezony takie jak ten [Wskazujesz na siebie].}
{105}{}{Moja krypta zosta³a zaatakowana przez supermutantów, wszystkich co próbowali siê broniæ wyciêli w pieñ. Musicie nam pomóc!}
{106}{}{Tym razem nic. Czeœæ.}
{107}{}{Chyba ju¿ pójdê.}

{110}{}{Co wiesz o ludziach ze szpitala?}

{190}{}{Typy ze szpitala to przesz³oœæ. Za moj¹ namow¹ opuœcili wioskê.}
{191}{}{Tak. Nie zapomnia³em na nich splun¹æ kiedy opuszczali bramê wioski. Dotrzymam umowy... [Wyjmuje z plecaka pokaŸny worek kapsli.] Tylko na litoœæ bosk¹ zrób z nich po¿ytek.}
{192}{}{Dziêki!}

#WHAT IS THIS PLACE#

{200}{}{To miejsce, jak ju¿ wczeœniej wspomnia³em - Cieniste Piaski - to przyjazna enklawa poœród dzikiej pustyni. Mamy tutaj sklep, bar i szpital prowadzony przez tajemniczych typów. I tylko ta czêœæ miasta powinna ciê interesowaæ. Dalej nie wtykaj nosa w nieswoje sprawy.}

{201}{}{O co chodzi z inn¹ czêœci¹ miasta?}
{202}{}{Jakiego typu rzeczy mo¿na kupiæ w sklepie?}
{203}{}{Bar?}
{204}{}{Móg³byœ nieco wiêcej powiedzieæ o tych tajemniczych typach?}
{205}{}{Mam jeszcze inne pytania, niekoniecznie dotycz¹ce tego miejsca.}
{206}{}{Dziêki, chyba ju¿ pójdê.}

{207}{}{O co dok³adnie chodzi?}
{208}{}{Chcia³bym zapytaæ jeszcze o to miejsce.}

{210}{}{Nic co powinno ciê interesowaæ. Wspomina³em ju¿ ¿ebyœ nie wtr¹ca³ nosa w nieswoje sprawy?}

{211}{}{Oj, daj spokój. W³os ci z g³owy nie spadnie.}
{212}{}{W porz¹dku. Wybacz, mogê jeszcze o coœ zapytaæ?}
{213}{}{A wiêc tak traktujecie ka¿dego przyjezdnego? Mo¿e po prostu zaoszczêdzisz mi problemów i powiesz mi o co chodzi z tym miejscem?}	#Retoryka 60#

{214}{}{S³uchaj, zaczynasz mi dzia³aæ na nerwy. Nie wiem jak tam sk¹d pochodzisz, ale tutaj nie radzê byæ wœcibskim, a w³asne komentarze zachowaj dla siebie. Nie poruszaj wiêcej tego tematu.}
{215}{}{Wybacz, mogê jeszcze o coœ zapytaæ?}
{216}{}{Jasne. Wiêc o co chcesz jeszcze zapytaæ?}

{217}{}{Dobra. Mo¿e jednak bêdzie lepiej jak ci powiem, ni¿ jakbyœ mia³ sam do tego dochodziæ. Tam we wschodniej czêœci miasta znajduje siê farma, pracuj¹ tam ludzie niekoniecznie ze swojej woli. Oni zapewniaj¹ wiosce po¿ywienie.}
{218}{}{To chore...}

{219}{}{Co chcesz jeszcze wiedzieæ? o Cienistych Piaskach?}
##
{220}{}{Mamy dosyæ szeroki asortyment. Znajdziesz u nas podstawowe zaopatrzenie przed wyruszeniem na pustkowia.}
{221}{}{Mamy dosyæ szeroki asortyment. Znajdziesz u nas podstawowe zaopatrzenie przed wyruszeniem na pustkowia.}

{222}{}{Macie coœ odpowiedniego na supermutantów?}
{223}{}{Kim jest Garl?}
{224}{}{Dziêki, mam jeszcze parê innych pytañ.}
{225}{}{Dziêki, muszê ju¿ iœæ.}

{230}{}{Cha cha! Nawet my, stra¿nicy bramy, nie mamy dobrych zabawek, ¿eby przeciwstawiæ siê mutantom. Dwa dni temu mia³a przybyæ tutaj op³acona karawana Zbrojeniowców ze sprzêtem. Coœ ich jednak zatrzyma³o.}

{231}{}{Karawana Zbrojeniowców?}
{232}{}{Mogê spróbowaæ jakoœ pomóc?}

{240}{}{Którego fragmentu nie rozumiesz? Tego z karawan?, czy ze Zbrojeniowcami?}

{241}{}{Kim s¹ Zbrojeniowcy?}
{242}{}{Karawany?}

{250}{}{Zbrojeniowcy, albo jak kto lubi Zbrojmistrzowie to ludzie, którzy zajmuj¹ siê wytwarzaniem uzbrojenia. Wokó³ g³ównej hali monta¿owej w ruinach Los Angeles rozlali beczki ze ¿r¹cym gównem i nazwali to miejsce Fortec¹.}

{252}{}{A te karawany, co to takiego?}
{253}{}{Dziêki, mam jeszcze kilka innych pytañ?}
{254}{}{Dziêki, chyba ju¿ pójdê.}

{255}{}{Nie wiem. Mo¿esz spróbowaæ popytaæ na mieœcie. To nie mój interes.}

{260}{}{Karawany to... karawany, kurwa! Je¿d¿¹ od miasta do miasta z towarami i wracaj¹ z innymi. Kwitnie handel. Nie wiem sk¹d ciebie wytrzasnêli, ale chcia³bym poznaæ to miejsce.}

{270}{}{[Przekazujesz w rêce Marka swojego pip-boya. Mark zwinnie operuje twoim pip-boyem i po kilkunastu sekundach oddaje ci go ze zaznaczon¹ lokacj¹.] Niedaleko od Fortecy znajduj¹ siê Gruzy, znajdziesz bez problemu. Tam te¿ jest cz³owiek, który pip-boye zna jak w³asne kieszenie.}
##
{271}{}{Okej, dziêki. Mam jeszcze kilka innych pyta?.}
{272}{}{Wspomina³eœ coœ o jakiœ karawanach...}

{280}{}{Nie wiem. Spróbuj popytaæ w barze, tam zawsze kolesie Garla siorbi¹ wódê.}
{281}{}{Okej, dziêki. Sprawdzê to.}

{290}{}{Garl? Garl to tak jakby nasz przywódca, ale i tak wiêkszoœæ robi samowolkê. Nie musisz nic wiêcej wiedzieæ.}
{291}{}{W porz¹dku. Mam inne pytania.}
##
{300}{}{No bar jak bar. Dobra atmosfera i tania wóda to podstawa. Chyba dziêki temu tylko mamy w tych stronach regularnych bywalców.}
##
{350}{}{Nikt mi nie chce wierzyæ, ¿e ich obecnoœæ tutaj sprowadzi na nas nieszczêœcie. Te typy to tak naprawdê s³ugusy supermutantów, ich mniejsi g³adkoskórzy kumplowie w œmiesznych fioletowych. Siedz¹ dzieñ w dzieñ nieprzerwanie w tym budynku i nie wpuszczaj¹ do œrodka nikogo. Gdyby tylko znaleŸæ dowód...}
{351}{}{JA jestem dowodem!}
{352}{}{Móg³bym dla ciebie znaleŸæ dowód, ale jestem biedny jak mysz krypciana. Chcia³bym coœ w zamian.}
{353}{}{Przykro to s³yszeæ. Muszê ju¿ spadaæ. Czeœæ!}

{354}{}{Ty? Co masz na myœli?}
{355}{}{Wspomnia³eœ, ¿e nosz¹ fioletowe szaty. Dajê s³owo, identyczne widzia³em, kiedy supermutanci napadali na nasz¹ kryptê.}
{356}{}{To nie wystarczy, muszê mieæ namacalny dowód. Musi byæ to coœ, co zbije Garla z nóg, coœ, co bez cienia w¹tpliwoœci wska¿e, ¿e brataj¹ siê z tymi dupkami.}
{357}{}{Wybacz, Mo¿e innym razem.}

{358}{}{W porz¹dku. Jestem w stanie poœwiêciæ wszystko, ¿eby dobraæ siê do dupy sukinsynom. Ach, niech bêdzie moja strata... dostaniesz ode mnie du¿¹ sumê kapsli.}
{359}{}{Przemyœla³em to. Móg³bym dla ciebie znaleŸæ dowód na tych purpurowych, ale jestem biedny jak mysz krypciana. Chcia³bym coœ w zamian.}

{360}{}{Jakieœ pomys³y gdzie zacz¹æ szukaæ?}
{361}{}{Od razu siê za to zabieram.}

{362}{}{Nie wiem, cholera jasna. W³aœnie dlatego powierzam to zadanie komuœ innemu! Mo¿esz zacz¹æ od wypytywania ludzi, czy to w barze, czy skoñczywszy w samym szpitalu. Nie mam kompletnie pojêcia jak ci pomóc.}
{363}{}{Dobra, tak zrobiê.}

#WHO ARE YOU#

{400}{}{Ja? Jestem Mark, a tu obok mój brat, Matt. Matt jest trochê wiesz... inny, ale za to potrafi sprawnie poci¹gn¹æ za cyngiel.}

{401}{}{W porz¹dku, a co tutaj robicie?}
{402}{}{Inny?}
{403}{}{Rozumiem. Mam jeszcze inne pytania.}
{404}{}{Rozumiem. Muszê ju¿ spadaæ.}
{405}{}{Muszê ju¿ spadaæ.}

{410}{}{A jak ci siê, cholera jasna, wydaje. Ja i Matt pilnujemy tutaj bramy przed ró¿nymi cwaniaczkami.}
{411}{}{Matt?}

{420}{}{No wiesz, za czasów swojej m³odoœci skaleczy³ siê w czo³o i pewien m¹dry lekarz stwierdzi³, ¿e dobrze mu bêdzie pomieszaæ w g³ówce. GwoŸdziem, wiesz? Nim odesz³a matka, przyrzek³em opiekowaæ siê Mattem. Ale coœ czujê, ¿e skurwiel poradzi³by sobie sam gdyby jeszcze potrafi³ sobie wychachmêciæ amunicjê.}
{421}{}{Matt - mój brat. No wiesz, za czasów swojej m³odoœci skaleczy³ siê w czo³o i pewien m¹dry lekarz stwierdzi³, ¿e dobrze mu bêdzie pomieszaæ w g³ówce. GwoŸdziem, wiesz? Nim odesz³a matka, przyrzek³em opiekowaæ siê Mattem. Ale coœ czujê, ¿e skurwiel poradzi³by sobie sam gdyby jeszcze potrafi³ sobie wychachmêciæ amunicjê.}
 
#THE TANDI#
{500}{}{O stary... nie mam pojêcia dlaczego jej szukasz, ale w sekrecie ci powiem, ¿e tutaj o ni¹ lepiej nie pytaæ. Szef upar³ siê odnaleŸæ j¹ za wszelk¹ cenê.}
{501}{}{Kim ona jest?}
{502}{}{Dlaczego jest mu tak potrzebna?}

{510}{}{Nie mam pojêcia. Wiem tylko tyle, ¿e mieszka³a tu zanim przybyliœmy. To dosyæ skomplikowane... Nie by³em wtedy kiedy ten gang zaj¹³ to miejsce. Wiem, ¿e byli nieŸle zszokowani tym, ¿e nie zastali tu ¿ywej duszy. Nie umiem nic wiêcej ci powiedzieæ na ten temat.}
{520}{}{A cholera jasna go tam wie. To furiat, a to miejsce przez niego z dniem siê stacza. Ratuje je tylko tania gorza³a.}

#FRIENDS#
{600}{}{Powinienem by³ ci powiedzieæ o tym na samym pocz¹tku. Ten sam kombinezon, co ty. Wpad³ tutaj jakiœ koleœ, próbowa³ nam coœ powiedzieæ, ale nie móg³ wydobyæ z siebie ani s³owa. Potem próbowa³ coœ ukraœæ ze sklepu, to go z ch³opakami z³apaliœmy i zamknêliœmy na farmie.}

{601}{}{Mogê siê z nim zobaczyæ?}
{602}{}{Nie móg³ wydobyæ z siebie ani s³owa?}
{603}{}{Da radê go jakoœ wyci¹gn¹æ?}

{610}{}{Jak uprosisz grzecznie stra¿nika to pewnie da radê. [Œmieje siê.]}

{620}{}{No mówiê ci. Wpad³ do wioski i zacz¹³ mi wymachiwaæ coœ rêkami. Pierwszy raz co? takiego widzia³em.}

{630}{}{Bêdzie ciê¿ko, mo¿e da³oby radê go wykupiæ za pewn¹ iloœæ kapsli.}
{631}{}{Kapsle?}

{640}{}{To jedyna tolerowana waluta na ca³ych pustkowiach. Przyk³adowo za 2 000 kapsli móg³bym sprawiæ sobie niez³y sprzêt na wyprawy po pustkowiach.}

#MUTANTS#
{700}{}{Jak TO musimy WAM pomóc?! Czy my wygl¹damy jak organizacja nios¹ca pokój i bezpieczeñstwo wszech pustkowiom? Z reszt¹ s³ysza³em ju¿ wczeœniej, co siê sta³o z wasz¹ krypt¹. Jest tutaj dwójka twoich przyjació³. Jedna kole¿anka w barze, kolega... jakby to powiedzieæ... odpracowuje winy.}
{701}{}{Kole¿anka?}
{702}{}{A ten co odpracowuje winy?} #friends#

{710}{}{Twoja kole¿anka przebywa teraz w barze. Trudno przeoczyæ to miejsce.}
{711}{}{Dziêki, pójdê ju¿.}
{712}{}{Dziêki, pozwól, ¿e zapytam o coœ innego.}

#
## Garl vs Jasper
#
{800}{}{Garl…}
{801}{}{Nie mo¿esz sobie o tak tu wchodziæ}
{802}{}{Nie tak siê umawialiœmy}

{803}{}{S³ysza³em o was parê niemi³ych rzeczy}
{804}{}{Musimy to sobie wyjaœniæ}

{805}{}{Któ¿by œmia³ w nasz¹ stronê wysuwaæ fa³szywe oskar¿enia?}

{806}{}{To nieistotne}
{807}{}{Nie by³o mnie tu chwilê}
{808}{}{Widzê, ¿e siê nieŸle urz¹dziliœcie}
{809}{}{Do rzeczy}
{810}{}{Jak wyjaœnicie to? *pokazuje holodysk*}
{811}{}{Ods³uchajmy kawa³ek}
{812}{}{Jasper 27 lipca 2163 roku}
#Fadeout
{813}{}{...¿e uzyskamy jak¹kolwiek przychylnoœæ lokalnej spo³ecznoœci...}

{814}{}{To bezczelna manipulacja!}
{815}{}{BluŸnierstwo!}
{816}{}{Holodysk zosta³ spreparowany!!!}
{817}{}{TAKI HOLODYSK MO¯NA ZROBIÆ SAMEMU W KA¯DYM DOMU Z PIP-BOYEM!!!}

{818}{}{Hmmm... to mo¿e byæ prawda}
{819}{}{Nie pomyœla³em o tym}
{820}{}{Dobra ch³opy, zawiajmy. Nic tu po nas}
{821}{}{A by³bym zapomnia³}
#6s
{822}{}{Wielka plama na ty³ku?}
{823}{}{Uwolniæ floatera}
{824}{}{Aarggghhh!!}
{825}{}{O kurwa co to jest!}
{826}{}{CO TO KURWA JEST?!}
{827}{}{Zabiæ to nim z³o¿y jaja!}

#QUEST CHILDRN#

{1000}{}{Znalaz³em dowód. Tkwi¹ w gównie, a¿ po same uszy.}

{1001}{}{[Szczerzy siê z uœmiechu.] Taaak? Co masz?}
{1002}{}{Holodysk na którym opisuj¹ dok³adnie, co bêd¹ chcieli zrobiæ z tym miejscem i z wami, nawet wspominaj¹ tam o tobie. Ale to jeszcze nic w porównaniu do tego, co mo¿na siê dowiedzieæ dalej!}

{1003}{}{Poka¿ mi to!}
{1004}{}{W porz¹dku.}
{1005}{}{Nie ma mowy.}

{1006}{}{[Nim nad¹¿asz wypowiedzieæ te s³owa, Mark wyrywa ci z r¹k Pip-Boya i zaczyna z prêdkoœci¹ œwiat³a czytaæ zapis transmisji.] ...obiekt ten wykazuje podejrzliwoœæ wobec naszej dzia³alnoœci. Sugerujemy, ¿e dla niego k¹piel w wirusie powinna trwaæ jeden koma piêæ d³u¿ej w porównaniu do innych obiektów...}
{1007}{}{Mark, ciszej... proszê.}

{1008}{}{Koniec. Miarka siê przebra³a. Zaraz pójdziemy z tym do Garla, w sensie do naszego przywódcy. W koñcu mi uwierzy.}
{1009}{}{W sensie, ¿e ja tam mam iœæ z tob¹?}

{1010}{}{Niestety. Garl musi wiedzieæ od kogo dosta³em ten holodysk, inaczej pomyœli, ¿e by go szukaæ opuœci³em bramê bez nadzoru.}
{1011}{}{Hmmm... wiêc chodŸmy.}
{1012}{}{A nie móg³byœ mi teraz daæ tych kapsli?}

{1013}{}{A w³aœnie, by³bym zapomnia³. Trzymaj te kapsle i idŸ sobie coœ kupiæ, bo jak tylko Garl to zobaczy to zacznie siê jatka.}
{1014}{}{Cooo? To ja te¿ bêdê w tym uczestniczy³?}
{1015}{}{Zaraz wracam.}

{1020}{}{Zobaczymy co Garl najpierw powie. Myœlê, ¿e jeœli coœ z tego bêdzie, a bêdzie, to staniesz sobie ewentualnie z boku i zobaczysz jak wypruwamy im flaki.}
#1015#

{1030}{}{Moment! Potrzebujesz jakieœ zabawki, bo gdy zacznie siê jatka nie powinieneœ zostawaæ z go³ymi rêkoma. Masz te kapsle i spraw sobie najpierw pukawkê.}
#1014#
#1015#

{1088}{}{Mark wrêcza ci worek kapsli.}
{1089}{}{Za znalezienie dostatecznego dowodu przeciwko tajniakom prowadz¹cym szpital zdobywasz 250 PD.}

{1090}{}{Jesteœ ju¿ gotowy by porozmawiaæ z Garlem, Rêk¹ Œmierci?}
{1091}{}{Wydaje mi siê, ¿e tak. Mo¿emy iœæ.}
{1092}{}{Daj mi jeszcze chwilê, ¿eby siê przygotowaæ.}

{1093}{}{To pospiesz siê, bo mnie ju¿ a¿ nosi. Ahhh... czujê zapach krwi i zgnilizny w powietrzu.}
{1094}{}{[KONIEC]}

# Dialogue with Darion's building's guard #

{1100}{}{Przesuñ siê. Mam wa¿n¹ sprawê do obgadania z szefem.}

{1101}{}{Mark...}
{1102}{}{To przestaje byæ œmieszne.}

{1103}{}{Spierdalaj.}
{1104}{}{A teraz siê przesuwaj.}

{1105}{}{Znowu zaczynasz?}
{1106}{}{Od ostatniego razu siê pozmienia³o.}
{1107}{}{Szef mi zakaza³ ciê wpuszczaæ.} #oredered to not
{1108}{}{Wypierdalaj.} #fuck off

{1109}{}{A co powiedzia³?} #what ordered to?
{1110}{}{¯ebyœ wypierdala³.} #to you fuck off
{1111}{}{Mam ci na piœmie to zostawiæ, ¿eby to do ciebie trafi³o?}

{1112}{}{O ty kurwa...}
{1113}{}{JA CI ZAPIERDOLE, KURWA!}

{1114}{}{O ¿esz, ty chuju kurwa.}

{1115}{}{CO TAM SIÊ ODPIERDALA?!}

{1116}{}{To siê porobi³o...}

{1117}{}{Doje¿d¿amy skurwieli.}

# Dialog z Garlem przed rozbojem w szpitalu #

{1200}{}{Mark powinienem by³ ciê od razu odjebaæ}
{1201}{}{Ale dam ci jeszcze szansê wyjaœniæ...}
{1202}{}{WYJAŒNIÆ DLACZEGO DALEJ}
{1203}{}{MIMO ZAKAZU}
{1204}{}{WCHODZISZ TUTAJ}
{1205}{}{SIEJESZ ZAMÊT}
{1206}{}{I MARNUJESZ MÓJ CENNY CZAS}
{1207}{}{I KIM JEST KURWA TEN CIPCIOK}
{1208}{}{S£UCHAM}

{1209}{}{Gadanie nic tu nie zmieni}
{1210}{}{Zobacz na to}
{1211}{}{*Wyci¹ga twojego Pip-Boya i odtwarza holotaœmê*}

{1212}{}{Syriuszu, poni¿ej przedstawiam ci moje obserwacje miejsca na wschód od Krypty 13...}
{1213}{}{Za chwilê us³yszysz liczby opisuj¹ce predyspozycje mieszkañców tej wioski do przemienienia}
{1214}{}{Wiem, ¿e nie by³eœ zwolennikiem mojego odejœcia w lekkim tego s³owa znaczeniu, ale wyniki moich obserwacji powinny zrekompensowaæ mój brak pos³uszeñstwa...} #fadeout #fadein
{1215}{}{Jeœli chodzi o ich przywódcê - Garla - ja widzê go w roli dowódcy nowego oddzia³u Armii Mistrza.}
{1216}{}{To du¿y kawa³ ludzkiego samca, pozostaj¹c optymistycznym s¹dzê, ¿e nie utraci inteligencji.}
{1217}{}{W¹tpliwoœci jedynie mo¿e sprawiaæ jego stan psychiczny oraz wielka plama na ty³ku bêd¹ca prawdopodobnie powik³aniami po chorobie z dzieciñstwa...}

{1220}{}{Doœæ, kurwa, doœæ}
{1221}{}{Zbieramy ch³opaków i zrobimy tam z tego szpitala burdel na kó³kach}
{1222}{}{Dawno nie mia³em okazji sobie postrzelaæ}


#Garl do gracza#

{1300}{}{Garl…} #Jasper
{1301}{}{Nie mo¿esz sobie o tak tu wchodziæ}
{1302}{}{Nie tak siê umawialiœmy}

{1303}{}{S³ysza³em o was parê niemi³ych rzeczy} #Garl
{1304}{}{Musimy to sobie wyjaœniæ}

{1305}{}{Któ¿by œmia³ w nasz¹ stronê wysuwaæ fa³szywe oskar¿enia?} #Jasper

{1306}{}{To nieistotne}
{1307}{}{Nie by³o mnie tu chwilê}
{1308}{}{Widzê, ¿e siê nieŸle urz¹dziliœcie}
{1309}{}{Do rzeczy}
{1310}{}{Jak wyjaœnicie to?}

{1311}{}{*wyjmuje holodysk*}
{1312}{}{Jasper 27 lipca 2163 roku}
{1313}{}{Jasper 27 lipca 2163 roku}
{1314}{}{Syriuszu, poni¿ej przedstawiam ci moje obserwacje miejsca na wschód od Krypty 13. }
#fadeout and in
{1315}{}{Drug¹ czêœæ wioski stanowi¹ niewolnicy reprezentuj¹cy najni¿sz¹ klasê typowych mieszkañców pustkowi}
{1316}{}{Nie stanowi¹ wiêkszego potencja³u, ani militarnego, ani intelektualnego}

{1317}{}{To bezczelna manipulacja!}
{1318}{}{BluŸnierstwo!} #Blasphemy!
{1319}{}{Holodysk zosta³ spreparowany!}

{1320}{}{Jak to UDOWODNISZ?!}
{1321}{}{TAKI HOLODYSK MO¯NA ZROBIÆ SAMEMU W KA¯DYM DOMU Z PIP-BOYEM!}
#6s
{1322}{}{Hmmm… to mo¿e byæ prawda}
{1323}{}{Nie pomyœla³em o tym}
{1324}{}{Dobra ch³opaki, spadamy}
{1325}{}{Nic tu po nas}

{1326}{}{Nie tak szybko!} #agatha

{1327}{}{Siostro Agatho, co ty wyprawiasz?!}

{1328}{}{S³ucham}
{1329}{}{Kontynuuj}

{1330}{}{Jeœli chcecie poznaæ prawdê…}
{1331}{}{...wejdŸcie na zaplecze}

{1332}{}{O w³aœnie, o tym nie pomyœla³em}

{1333}{}{Nie! Nie macie prawa tam wchodziæ!}

{1334}{}{Nawet nie masz pojêcia jak teraz rozpali³eœ moj¹ ciekawoœæ...}

{1335}{}{Uwolniæ floatera!}
{1336}{}{Aarggghh!}
{1337}{}{O kurwa co to jest!!}
{1338}{}{Co to kurwa jest!?}
{1339}{}{Zabiæ to nim z³o¿y jaja!}



{1380}{}{A ty, m³odzieniaszku }
{1381}{}{A ty, stary zgredzie...}
{1382}{}{A ty, dziewczynko...}
{1383}{}{A ty, stara panno...}

{1390}{}{Chcia³bym porozmawiaæ z tob¹ w moim miejscu.}
{1391}{}{Mo¿e bêd¹ z ciebie jeszcze ludzie.}

#Podziekowania dla gracza za rozwiazanie questa z Dziecmi Katedry#
{1400}{}{Hej, dziêki za rozwi¹zanie dla mnie problemu z purpurowymi. Ich obecnoœæ œci¹ga³a tutaj nieszczêœcie. Ale jeszcze jest jedna sprawa...}
{1401}{}{Hmmmm???}
{1402}{}{Garl chcia³ ciê widzieæ u siebie i prawdopodobnie ciebie zrekrutowaæ. Powiem tak... jak chcesz to pracuj dla niego, ale nied³ugo bêdziesz musia³ coœ zrobiæ przeciwko sobie, a wtedy i mnie i wielu te¿ nie bêdzie ju¿ tutaj w wiosce...}
{1403}{}{Nic nie rozumiem...}
{1404}{}{Jeszcze nic nie rozumiesz. Po prostu pracuj dla Garla, ale nie przekraczaj pewnej granicy, bo pójdziesz z nim na dno. Za jakiœ czas siê wiêcej rzeczy powyjaœnia.}
{1405}{}{Zagmatwane to co mówisz. Niemniej jednak postaram siê to zapamiêtaæ.}
{1406}{}{Mam nadziejê. Za nied³ugo wszystko tu zacznie siê zmieniaæ. A teraz w czym mogê ci pomóc?}

{4000}{}{Za pozbycie siê szpiegów supermutantów z Cienistych piasków zdobywasz 500 PD.}
