{200}{}{Jestem Oswald, zarz¹dca obozu. A ty ma³a gnida, która jak widaæ siê zagubi³a. Nim ciê wypcham o³owiem, mów z czym do mnie przychodzisz?}
{201}{}{Ktoœ spiskuje przeciwko wam. Jest w barze poza obozem. Planuje od d³u¿szego czasu zbuntowaæ niewolników i doprowadziæ do strzelaniny!}
{202}{}{W³aœciwie to ju¿ wychodzi³em.}

{210}{}{To jakiœ nieœmieszny dowcip? Co jest z wami?! Dlaczego wpuszczacie mi takie œcierwo?! Rozjebaæ to!}
{211}{}{Nie, nie! Czekaj!}

{220}{}{Kto taki?}
{221}{}{Nie przedstawi³ mi siê. £ysy koleœ z zawieszon¹ mask¹ gazow¹ u szyi. No i jeszcze ta peleryna!}

{230}{}{Co raz bardziej utwierdzam siê w przekonaniu, ¿e przeprowadzka do tego miejsca uœpi³a czujnoœæ Garla... Mogê tylko powiedzieæ dziêki, bo wystarczy nam ju¿ jeden kapuœ. [Wyci¹ga karabin.]}
{231}{}{Kurwa! Tak mi siê odp³acacie?}