{100}{}{Widzisz starego faceta. Wygl¹da na zajêtego napraw¹ radiostacji.}
{102}{}{Widzisz Felixa. Nas³uchuje czêstotliwoœci.}

{110}{}{Pieprzony szajs...}
{111}{}{Dzia³aj ty pieprzona kupo z³omu! I kupo gówna! DZIA£AJ KURWA!}
{112}{}{Chyba mnie zaraz krew zaleje...}

{150}{}{[Mê¿czyzna z którym próbujesz porozmawiaæ wygl¹da na bardzo zajêtego. Zdaje siê przeklinaæ w myœlach na stary zardzewia³y sprzêt, który nie chce dzia³aæ. Masz wra¿enie, ¿e przerwanie mu w pracy otworzy wrota piekie³.]}
{151}{}{Ekhem...}
{152}{}{[OdejdŸ.]}

{160}{}{[Mê¿czyzna powoli odwraca g³owê w twoj¹ stronê ze zgrymaszon¹ min¹ nieustannie tkwi¹c w zgiêtej pozycji.] Czego?! Tu cz³owiek pracuje, a nie jak reszta tego œmierdz¹cego wód¹ miejsca.}
{161}{}{Potrzebujesz pomocy?}
{162}{}{Eeee, chyba jednak nic.}

{170}{}{TO PRZESTAÑ MI PRZESZKADZAÆ!}
{171}{}{NIE DOTYKAJ TEGO!}
{172}{}{ZARAZ SIÊ WKURWIÊ!}
{173}{}{KONIEC TEGO DOBREGO!}

{180}{}{S³uchaj, nie widzia³em ciê tu wczeœniej, wiêc jest cieñ nadziei, ¿e znasz siê na tym ustrojstwie. Wiêc jak?}
{181}{}{[Sk³am.] Liznê³o siê tam co nie co.}
{182}{}{Tak.}
{183}{}{Nie.}

{190}{}{NO TO NIE ZAWRACAJ MI DUPY.}
{191}{}{TY IDIOTO. TERAZ TO JU¯ NIGDY SIÊ NIE W£¥CZY.}

{200}{}{To rzuæ, proszê, na to okiem. Tylko ostro¿nie z tym sprzêtem, to wszystko ma ze 200 lat.}
{201}{}{W porz¹dku. Zobaczê, co siê da z tym zrobiæ.}

{210}{}{Ostró¿nie z tym, to delikatny sprzêt.}
{211}{}{Zajmij siê tym, mi ju¿ pêcherze na palcach od tego gówna siê zrobi³y.}

{240}{}{O cz³owieku, nie wiem jak ci mam dziêkowaæ. Jak tyœ tego dokona³? Niewa¿ne... jak mam ci siê odwdziêczyæ?}
{241}{}{Co tutaj robisz?}

{250}{}{Nas³uchujê ró¿nych czêstotliwoœci i ustalam si³ê sygna³u. Dziêki temu wzglêdnie znamy pozycjê supermutantów.}
{251}{}{I co? Podchodz¹ co raz bli¿ej?}
{252}{}{Mo¿esz pods³uchaæ, o czym rozmawiaj¹?}

{260}{}{Tak, ostatnio mocno przesunêli siê na wschód, ale momentalnie siê zatrzymali. Czasami sygna³ jest tak silny, ¿e odnoszê wra¿enie, ¿e pochodzi z tego miejsca...}
{261}{}{Z tej wioski?}

{270}{}{Tak. Dziwne, co nie? Nawet specjalnie zapisa³em sobie je na magnetowidzie i przegra³em na holodyski. Niestety, ja nie jestem w stanie ich zdeszyfrowaæ.}
{271}{}{Móg³byœ mi daæ taki holodysk? Mo¿e mi siê uda coœ z nim wykombinowaæ.}

{280}{}{Jasne. Jeœli tobie uda³o siê w dwie minuty osi¹gn¹æ to, czego ja próbowa³em dniami, to dlaczego by nie? [Wyjmuje jeden holodysk z urz¹dzenia rejestruj¹cego i wrêcza ci go.] Proszê.}
{282}{}{Dziêki. Na mnie czas.}

{290}{}{Niestety, nie mogê. Wszystko jest zaszyfrowane na potêgê. Tutaj trzebaby by³o mieæ klucz deszyfruj¹cy i dzia³aj¹cego Pip-Boya.}
{291}{}{Dziêki. A ci mutanci, s¹ co raz bli¿ej, nie?}

{300}{}{Za naprawê radiostacji zyskujesz 200 PD.}

{310}{}{Hej, jeszcze raz dziêki za naprawê radia!}

{500}{}{To twoja robota! Po¿a³ujesz tego!}
{501}{}{Co tam siê kurwa dzieje?!}

{600}{}{NIEEEEE!!!}
{601}{}{TY GNIDO, OBUD SIÊ}
#Wszystkie tranzystory popalone!


{605}{}{Zwarcie elektryczne powoduje przep³yw pr¹du elektrycznego przez twoje cia³o powalaj¹c cie na ziemiê.}

{610}{}{Najpierw mi pomagasz naprawiæ ten syf, a teraz go niszczysz?! Co z tob¹?!}
{611}{}{Nic nie jest takie proste jak myœlisz...}
{612}{}{Chyba ju¿ pójdê...}

{620}{}{Jak pójdziesz?! Le¿ysz na ziemi i nawet nie jesteœ w stanie wstaæ. Kto ci kaza³ to zrobiæ?!}
{621}{}{Ten... goœæ z baru...}
{622}{}{Pierdol siê.}

{625}{}{Sam siê o to prosi³eœ.}

{630}{}{A co tu jest nie do zrozumienia?! Przyszed³eœ i zniszczy³eœ coœ nad czymœ pracowa³em miesi¹cami! Ktoœ ci kaza³ to zrobiæ!?}
#621
#622

{640}{}{No piêknie... znowu siê ktoœ przypierdala do starego Felixa! Masz mi jeszcze coœ do powiedzenia?}
{641}{}{Tak, pierdol siê!}
{642}{}{On chce ci zaoferowaæ lepszy sprzêt do pracy.}
{643}{}{To wszystko.}

{650}{}{[Felix wpada w lekk¹ konsternacjê. Jednak po chwili ju¿ nie takim gniewnym tonem jak wczeœniej odpowiada.] Jaki?}
{651}{}{Na pewno nie taki syf, co mia³eœ tutaj.}

{660}{}{Mo¿esz mnie zaprowadziæ do niego?}
{661}{}{Tak.}
{662}{}{Um.. nie.}

{670}{}{W takim razie zap³acisz mi za to...}
{671}{}{Dobra, ju¿ dobra. ChodŸ za mn¹.}
{672}{}{Ups.}

{700}{}{S³uchaj goœciu...}
{701}{}{Odebra³eœ mi to co kocham}
{702}{}{Tak przynajmniej mówi ten cz³owiek}
{703}{}{Zbiera³em ten sprzêt przez wiêksz¹ czêœæ mojego ¿ycia}
{704}{}{Do czasu kiedy wys³a³eœ swojego kochasia...}
#A
{705}{}{CO masz na swoje usprawiedliwienie nim wezwê Chanów!}
{706}{}{Porozmawiajmy spokojnie na zewn¹trz - nie tutaj}
{707}{}{Tam wszystko sobie wyjaœnimy}
{708}{}{No ja mam nadziejê}
#B
{709}{}{Ale s³ysza³em, ¿e masz mi coœ mimo to do zaoferowania}
{710}{}{Wiêc jestem i s³ucham!}
#706
#707
#708

#Po wytlumaczeniu i rozmowa prywatna Tycho z Felixem

{720}{}{...bêdzie to...ta piê... góry}
{721}{}{Ale czy... Cha... za¿...?}
{722}{}{Ja...nie...pójdzie...na pewno}
{723}{}{Zgo...dziejê...kasz}
{724}{}{...z nim}
{725}{}{..OK...}

#Quest od Tycho - cicha metoda
#hej dzieki za napraweee
{800}{}{Hej, widzia³em, ¿e lubisz zapaliæ. Generalnie ja nie palê, ale tobie mo¿e siê przydaæ. Trzymaj. [Wrêczasz mu paczkê papierosów.]}
{801}{}{W³aœciwie to pozosta³o mi tylko parê szlugów, a ja czujê potrzebê. Dziêki!}
{802}{}{Eee... nic.}
{805}{}{...Jeœli chcê majstrowaæ przy radiu, muszê odwróciæ jego uwagê...}
{806}{}{Szkoda, ¿e fajki mi siê skoñczy³y...}

#Rebelia
{1000}{}{Cholera... to siê porobi³o...}