{200}{}{Ta robota mnie dobija...}
{201}{}{Nie by³em na zewn¹trz od miesiêcy.}
{202}{}{Praca czyni wolnym, podobno...}
{203}{}{S³oñce nie u³atwia sprawy.}
{204}{}{Mam nadziejê, ¿e powiesimy za jaja tego, co nam taki los urz¹dzi³.}
{205}{}{Jeszcze miesi¹c i wiêcej ju¿ nie poci¹gne.}
{206}{}{Galachad, chuj ci na imiê, ty skurwysynie...}


{210}{}{Hrrrr...}
{211}{}{uch... chyba mia³em z³y sen.}
{212}{}{uch... œni³o mi siê, ¿e wywaliœmy Szakali na zbity pysk.}