{100}{}{Widzisz starego faceta. Wygl¹da na zajêtego napraw¹ radiostacji.}
{102}{}{Widzisz Felixa. Nas³uchuje czêstotliwoœci.}

{191}{}{TY IDIOTO. TERAZ TO JU¯ NIGDY SIÊ NIE W£¥CZY.}

{210}{}{[Widzisz przestarza³ego grota, ze œrodka wychodzi mnóstwo kabli, niektóre s¹ ze sob¹ prowizorycznie posklejane. Boisz siê dotkn¹æ cokolwiek, masz wra¿enie, ¿e to wszystko jak nie wybuchnie, to siê rozpadnie. Mimo wszystko widzisz kilka logicznych rozwi¹zañ.]}
{211}{}{[Pod³¹cz kabel z czerwon¹ koñcówk¹ do pomarañczowego wejœcia. Wydaje ci siê, ¿e pomarañczowa barwa wejœcia wyblak³a wskutek czasu.]}
{212}{}{[Pod³¹cz kabel z czerwon¹ koñcówk¹ do pomarañczowego wejœcia.]}
{213}{}{[Pod³¹cz kabel z czerwon¹ koñcówk¹ do ¿ó³tego wejœcia.]}
{214}{}{[Wciskaj przyciski z przodu sprzêtu w losowej kolejnoœci.]}
{215}{}{[Uderz mocno w bok sprzêtu.]}
{216}{}{[Uderz mocno od góry sprzêtu.]}
{217}{}{[Poli¿ poszarpany przewód jêzykiem. Mo¿e to coœ da.]}
{218}{}{[W³¹cz i wy³¹cz.]}
{219}{}{[LEAVE IT ALONE] I need to save my game.}

{225}{}{[Nic siê nie dzieje.]}
{226}{}{[Us³ysza³eœ w œrodku jakiœ klik.]}

{230}{}{[Podczas w³¹czania s³ychaæ charakterystyczny pstryk, od razu zaczyna odbieraæ czêstotliwoœæ na której s³ychaæ utwór dawno ju¿ zapomnianego zespo³u.}
{231}{}{[GOTOWE]}

{250}{}{ZOSTAW TEN SPRZÊT W SPOKOJU}
{251}{}{Wygl¹da na to, ¿e wszystko dzia³a jak nale¿y i nie powinno siê zak³ócaæ tego stanu rzeczy.}

{300}{}{[Przed sob¹ masz ponownie radiostacjê Felixa]}
{301}{}{[Spróbuj zamontowaæ uk³ad, który ukrad³eœ Felixowi.]}
{302}{}{[Zacznij losowo wsciskiwaæ przyciski.]}
{303}{}{[OdejdŸ.]}

{305}{}{Pomyœlnie instalujesz uk³ad.}
{306}{}{Zdobywasz 100 PD.}
#303

{310}{}{Hej, zostaw to!}