### Hello First Time ###

{300}{}{I? I? Co by³o dalej?}

{301}{}{Có¿…}
{302}{}{Jeszcze nie zd¹¿y³em zaimplementowaæ, ale wszystko idzie w dobrym kierunku…}

{303}{}{Nie wiem co na to rada, ale uwa¿am, ¿e jeœli coœ ma ocaliæ kryptê 55 to bêdzie w³aœnie to... to...}
{304}{}{...no w³aœnie, jak to nazywasz?}

{305}{}{Gra wideo?}

{306}{}{Gra wideo… no tak}
{307}{}{Potrzeba matk¹ wynalazków!}
{308}{}{A wy co myœlicie, rado?}

{309}{}{Chcê wiêcej!}

{310}{}{Hmmmm…}
{311}{}{Uwa¿am, ¿e wszystko bêdzie lepsze od s³abych komedii ze s³abymi aktorami}

{312}{}{Musimy zaryzykowaæ i daæ autorowi wszystkie potrzebne œrodki, ¿eby ukoñczy³ projekt jak najszybciej}
{313}{}{Pozosta³o niewiele czasu...}

{314}{}{Pozosta³o niewiele czasu...}

{315}{}{Pe³na zgoda. Co potrzebujesz twórco?}

{316}{}{No…}
{317}{}{Przyda³oby siê pewne wsparcie finansowe…}
{318}{}{Jakieœ dziewczyny do mojej kwatery…}
{319}{}{Gad¿ety}
{320}{}{I naprawcie mi w koñcu t¹ pieprzon¹ klimatyzacjê!}

{321}{}{To ma³a cena za ratunek krypty}
{322}{}{Jeszcze coœ?}


{323}{}{I jeszcze p¹czki do tego!}
