/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef TEAMS_H
#define TEAMS_H

/*********************************************************
 define file for Team Numbers.

 All defines in this file are to be prepended with TEAM_

 Contents of the File:
        I.      Team Numbers
*********************************************************/

#define TEAM_PLAYER                             (0)
#define TEAM_ARROYO                             (1)
#define TEAM_BRAHMIN                            (2)
#define TEAM_RAT                                (3)
#define TEAM_SCORPION                           (4)
#define TEAM_MANTIS                             (5)
#define TEAM_DEATH_CLAW                         (6)
#define TEAM_SPORE_PLANT                        (7)
#define TEAM_KHANS								(8)
#define TEAM_1PIJAK								(9)
#define TEAM_2PIJAK								(10)
#define TEAM_BIMBROWNICY						(11)
#define TEAM_BRODEAD_MUTS						(12)
#define TEAM_SHADY_CHILD						(13)
#define TEAM_SHADY_MUTANTS						(14)
#define TEAM_REBELLION 		    				(15)
#define TEAM_MB_MUTANTS 		    			(16)
#define TEAM_CHILDRN 		    			    (17)
#define TEAM_MAGAZINE 		    			    (18)
#define TEAM_V13_SUPERMUTANTS 		    		(19)
#define TEAM_SHADY_CAMP_CAVE_SIMON 		    	(20)
#define TEAM_SHADY_CAMP_CAVE_ENEMY 		    	(21)
#define TEAM_SUPER_MUTANT        		    	(22)
#define TEAM_CARAVAN             		    	(23)
#define TEAM_BANDIT             		    	(24)
#define TEAM_RND_BRAHMIN             		    (25)
#define TEAM_DUC                     		    (26)
#define TEAM_V13                    		    (27)
#define TEAM_RANGERS                  		    (28)
#define TEAM_ISAAC                    		    (29)
#define TEAM_SHADY_NEUTRAL                      (30)

#endif // TEAMS_H
